[pytest]
markers =
    all: Все тесты
    seller: Тесты продавца
    client: Тесты клиента

    company_details: Тесты данных компании
    seller_create_tour: Тесты создания тура продавцом
    other: Другое
    basket: Корзина
    debug: Для отладки в gitlab
