import pytest
from playwright.sync_api import Page
from fixtures.all import intercept_requests, db_connection, photo_paths, db_connection_dev_logs  
from pages.seller.seller_tours.seller_create_update_tour.seller_create_update_tour import SellerCreateUpdateTour
from pages.seller.seller_tours.seller_create_update_tour.seller_create_update_tour_waypoints.seller_create_update_tour_waypoints import SellerCreateUpdateTourWaypoints
import allure
from Locators.loc_all_directories import ALL_LOCATORS
from Assertions.seller.seller_tours.seller_tour_card.seller_tour_parametrs.assert_seller_tour_parametrs import AssertionsTourParametrs
from Assertions.seller.seller_tours.seller_tour_card.seller_tour_parametrs.seller_tour_waypoints.assert_seller_tour_waypoints import AssertionsTourWaypoints
from Constants.seller.seller_auth.const_seller_auth import (
    SELLER_LOGIN4_TOURS,
    SELLER_PASSWORD1
)
from Constants.seller.seller_tours.seller_tour_card.seller_tour_parametrs.const_seller_tour_parametrs import (
    SELLER_TOUR_TITLE1,
    SELLER_TOUR_TITLE1_SLUG,
    SELLER_TOUR_STATUS1_NO_SAVE,
    SELLER_TOUR_STATUS2_DRAFT,
    SELLER_TOUR_STATUS3_ALL_FILL,
    SELLER_TOUR_STATUS4_ON_CHECK,
    SELLER_TOUR_DESCRIPTION1,
    SELLER_TOUR_DESCRIPTION1_IN_DB,
    SELLER_TOUR_DESCRIPTION2,
    SELLER_TOUR_DESCRIPTION2_IN_DB,
    SELLER_TOUR_INPRICE1,
    SELLER_TOUR_INPRICE1_IN_DB,
    SELLER_TOUR_INPRICE2,
    SELLER_TOUR_INPRICE2_IN_DB,
    SELLER_TOUR_NOT_IN_INPRICE1,
    SELLER_TOUR_NOT_IN_INPRICE1_IN_DB,
    SELLER_TOUR_NOT_IN_INPRICE2,
    SELLER_TOUR_NOT_IN_INPRICE2_IN_DB,
    SELLER_TOUR_HOTELID,
    SELLER_TOUR_HOTELID_LINK,
    SELLER_TOUR_HOTELID2,
    SELLER_TOUR_HOTELID_LINK2,
    SELLER_TOUR_CLASS_DISABLE,
    #Маршрут
    SELLER_TOUR_ROUTE_TIMEZONE3,
    SELLER_TOUR_ROUTE_TIMEZONE4,
    SELLER_TOUR_TIMEZONE4,
    SELLER_TOUR_TIMEZONE3,
    SELLER_TOUR_ROUTE_COLLECTION_POINT_DAY_CLASS_DISABLED,
    SELLER_TOUR_ROUTE_COLLECTION_POINT_ADDRESS1,
    SELLER_TOUR_ROUTE_COLLECTION_POINT_ADDRESS2,
    SELLER_TOUR_ROUTE_COLLECTION_POINT_CORDS1,
    SELLER_TOUR_ROUTE_COLLECTION_POINT_CORDS2,
    SELLER_TOUR_ROUTE_COLLECTION_POINT_DAY1,
    SELLER_TOUR_ROUTE_COLLECTION_POINT_TIME1,
    SELLER_TOUR_ROUTE_COLLECTION_POINT_TIME2,
    SELLER_TOUR_ROUTE_COLLECTION_POINT_TITLE1,
    SELLER_TOUR_ROUTE_COLLECTION_POINT_TITLE2,
    SELLER_TOUR_ROUTE_COLLECTION_POINT_DESCRIPTION1,
    SELLER_TOUR_ROUTE_COLLECTION_POINT_DESCRIPTION2,
    SELLER_TOUR_ROUTE_COLLECTION_POINT_CORDS1_IN_DB,
    SELLER_TOUR_ROUTE_COLLECTION_POINT_CORDS2_IN_DB,
    SELLER_TOUR_ROUTE_COLLECTION_POINT_TIME1_IN_DB,
    SELLER_TOUR_ROUTE_COLLECTION_POINT_TIME2_IN_DB,
    SELLER_TOUR_ROUTE_COLLECTION_POINT_DESCRIPTION1_IN_DB,
    SELLER_TOUR_ROUTE_COLLECTION_POINT_DESCRIPTION2_IN_DB
) 

#Отели
#Нет теста частых вопросов
#Нет теста для отзыва
#Нет теста для смены статусов после модерации

@allure.feature('Продавец')
@allure.story('Создание тура')
@pytest.mark.all
@pytest.mark.seller
@pytest.mark.seller_create_tour
class TestSellerCreateUpdateTour:

    @allure.title('Создание тура начиная с названия')
    def test_seller_create_tour1 (self, page: Page, intercept_requests, db_connection, db_connection_dev_logs):
        createtour = SellerCreateUpdateTour(page)
        assertions = AssertionsTourParametrs(page)
        createtour.delete_tour_in_db(db_connection,  db_connection_dev_logs, SELLER_TOUR_TITLE1)
        createtour.seller_goto_create_tour_old(page, SELLER_LOGIN4_TOURS, SELLER_PASSWORD1)
        assertions.check_operator_tour_param_button_create_inactive()
        assertions.check_svg_near_text('Основное')
        assertions.check_create_tour_all_fields_disable(SELLER_TOUR_CLASS_DISABLE)
        assertions.check_operator_tour_create_status_front( page, SELLER_TOUR_STATUS1_NO_SAVE )
        createtour.seller_create_tour_fill_general(page, SELLER_TOUR_TITLE1)
        assertions.check_operator_tour_param_button_create_active()
        assertions.check_img_near_text('Основное')
        assertions.check_create_tour_in_db( db_connection, SELLER_TOUR_TITLE1, 1, 6, 1, SELLER_TOUR_TITLE1_SLUG, 717)
        assertions.check_operator_tour_param_button_on_review_inactive()
        assertions.check_request_statuses(intercept_requests)
        createtour.delete_tour_in_db(db_connection,  db_connection_dev_logs, SELLER_TOUR_TITLE1)


    @allure.title('Создание тура начиная с типа автопутешествия')
    def test_seller_create_tour2 (self, page: Page, intercept_requests, db_connection, db_connection_dev_logs):
        createtour = SellerCreateUpdateTour(page)
        assertions = AssertionsTourParametrs(page)
        createtour.delete_tour_in_db(db_connection, db_connection_dev_logs, SELLER_TOUR_TITLE1)
        createtour.seller_goto_create_tour_old(page, SELLER_LOGIN4_TOURS, SELLER_PASSWORD1)
        assertions.check_operator_tour_param_button_create_inactive()
        assertions.check_svg_near_text('Основное')
        assertions.check_create_tour_all_fields_disable(SELLER_TOUR_CLASS_DISABLE)
        assertions.check_operator_tour_create_status_front( page, SELLER_TOUR_STATUS1_NO_SAVE )
        createtour.click_element('Тип автопутешествия в параметрах тура')
        createtour.click_element('Автопутешествие в параметрах тура')
        createtour.click_element('Ответственный сотрудник в параметрах тура')
        createtour.click_element('Первый сотрудник в параметрах тура') 
        createtour.fill_element('Название тура в параметрах тура', SELLER_TOUR_TITLE1) 
        page.wait_for_timeout(500)
        assertions.check_operator_tour_param_button_create_active()
        assertions.check_img_near_text('Основное')
        assertions.check_operator_tour_create_status_front( page, SELLER_TOUR_STATUS2_DRAFT)
        assertions.check_create_tour_in_db( db_connection, SELLER_TOUR_TITLE1, 1, 6, 1, SELLER_TOUR_TITLE1_SLUG, 717)
        assertions.check_operator_tour_param_button_on_review_inactive()
        assertions.check_request_statuses(intercept_requests)
        createtour.delete_tour_in_db(db_connection, db_connection_dev_logs, SELLER_TOUR_TITLE1)


    @allure.title('Создание тура начиная c ответственного')
    def test_seller_create_tour3 (self, page: Page, intercept_requests, db_connection, db_connection_dev_logs):
        createtour = SellerCreateUpdateTour(page)
        assertions = AssertionsTourParametrs(page)
        createtour.delete_tour_in_db(db_connection, db_connection_dev_logs, SELLER_TOUR_TITLE1)
        createtour.seller_goto_create_tour_old(page, SELLER_LOGIN4_TOURS, SELLER_PASSWORD1)
        assertions.check_operator_tour_param_button_create_inactive()
        assertions.check_svg_near_text('Основное')
        assertions.check_create_tour_all_fields_disable(SELLER_TOUR_CLASS_DISABLE)
        assertions.check_operator_tour_create_status_front( page, SELLER_TOUR_STATUS1_NO_SAVE )
        createtour.click_element('Ответственный сотрудник в параметрах тура')
        createtour.click_element('Первый сотрудник в параметрах тура') 
        createtour.click_element('Тип автопутешествия в параметрах тура')
        createtour.click_element('Автопутешествие в параметрах тура')
        createtour.fill_element('Название тура в параметрах тура', SELLER_TOUR_TITLE1) 
        assertions.check_operator_tour_param_button_create_active()
        assertions.check_img_near_text('Основное')
        assertions.check_operator_tour_create_status_front( page, SELLER_TOUR_STATUS2_DRAFT)
        assertions.check_create_tour_in_db( db_connection, SELLER_TOUR_TITLE1, 1, 6, 1, SELLER_TOUR_TITLE1_SLUG, 717)
        assertions.check_operator_tour_param_button_on_review_inactive()
        assertions.check_request_statuses(intercept_requests)
        createtour.delete_tour_in_db(db_connection, db_connection_dev_logs, SELLER_TOUR_TITLE1)


    @allure.title('Создание тура. Выбор предварительного бронирования')
    def test_seller_create_tour4 (self, page: Page, intercept_requests, db_connection, db_connection_dev_logs):
        createtour = SellerCreateUpdateTour(page)
        assertions = AssertionsTourParametrs(page)
        createtour.delete_tour_in_db(db_connection, db_connection_dev_logs, SELLER_TOUR_TITLE1)
        createtour.seller_goto_create_tour_old(page, SELLER_LOGIN4_TOURS, SELLER_PASSWORD1)
        assertions.check_operator_tour_param_button_create_inactive()
        assertions.check_svg_near_text('Основное')
        assertions.check_create_tour_all_fields_disable(SELLER_TOUR_CLASS_DISABLE)
        assertions.check_operator_tour_create_status_front( page, SELLER_TOUR_STATUS1_NO_SAVE )
        createtour.click_element('Ответственный сотрудник в параметрах тура')
        createtour.click_element('Первый сотрудник в параметрах тура') 
        createtour.click_element('Тип автопутешествия в параметрах тура')
        createtour.click_element('Автопутешествие в параметрах тура')
        createtour.fill_element('Название тура в параметрах тура', SELLER_TOUR_TITLE1) 
        assertions.check_operator_tour_param_button_create_active()
        assertions.check_img_near_text('Основное')
        assertions.check_operator_tour_create_status_front( page, SELLER_TOUR_STATUS2_DRAFT)
        assertions.check_create_tour_in_db( db_connection, SELLER_TOUR_TITLE1, 1, 6, 1, SELLER_TOUR_TITLE1_SLUG, 717)
        assertions.check_operator_tour_param_button_on_review_inactive()
        assertions.check_create_tour_in_db_with_reservations(db_connection, SELLER_TOUR_TITLE1, 1, 6, 1, 717, False)
        assertions.verify_toggle_checked_by_xpath(page,'Только предварительное бронирование тогл в параметрах тура', 'false')
        createtour.click_element('Только предварительное бронирование тогл в параметрах тура')
        assertions.verify_toggle_checked_by_xpath(page,'Только предварительное бронирование тогл в параметрах тура', 'true')
        createtour.click_element('Кнопка Сохранить в создании тура продавца')
        page.wait_for_timeout(1000)
        assertions.check_create_tour_in_db_with_reservations(db_connection, SELLER_TOUR_TITLE1, 1, 6, 1, 717, True)
        createtour.click_element('Только предварительное бронирование тогл в параметрах тура')
        assertions.verify_toggle_checked_by_xpath(page,'Только предварительное бронирование тогл в параметрах тура', 'false')
        createtour.click_element('Кнопка Сохранить в создании тура продавца')
        page.wait_for_timeout(1000)
        assertions.check_create_tour_in_db_with_reservations(db_connection, SELLER_TOUR_TITLE1, 1, 6, 1, 717, False)
        assertions.check_request_statuses(intercept_requests)
        createtour.delete_tour_in_db(db_connection, db_connection_dev_logs, SELLER_TOUR_TITLE1)


    @allure.title('Создание тура. Сохранение жанров в туре')
    def test_seller_create_tour5 (self, page: Page, intercept_requests, db_connection, db_connection_dev_logs):
        createtour = SellerCreateUpdateTour(page)
        assertions = AssertionsTourParametrs(page)
        createtour.delete_tour_in_db(db_connection, db_connection_dev_logs, SELLER_TOUR_TITLE1)
        createtour.seller_goto_create_tour_old(page, SELLER_LOGIN4_TOURS, SELLER_PASSWORD1)
        assertions.check_operator_tour_param_button_create_inactive()
        assertions.check_svg_near_text('Основное')
        assertions.check_create_tour_all_fields_disable(SELLER_TOUR_CLASS_DISABLE)
        assertions.check_operator_tour_create_status_front( page, SELLER_TOUR_STATUS1_NO_SAVE )
        createtour.seller_create_tour_fill_general(page, SELLER_TOUR_TITLE1)
        assertions.check_operator_tour_param_button_create_active()
        assertions.check_img_near_text('Основное')
        assertions.check_create_tour_in_db( db_connection, SELLER_TOUR_TITLE1, 1, 6, 1, SELLER_TOUR_TITLE1_SLUG, 717)
        assertions.check_svg_near_text('Жанры')
        assertions.verify_checkbox_state(page, '1й жанр в параметрах тура', False)
        createtour.click_element('1й жанр в параметрах тура')
        assertions.check_img_near_text('Жанры')
        assertions.verify_checkbox_state(page, '1й жанр в параметрах тура', True)
        assertions.verify_checkbox_state(page, '3й жанр в параметрах тура', False)
        createtour.click_element('3й жанр в параметрах тура')
        assertions.verify_checkbox_state(page, '3й жанр в параметрах тура', True)
        createtour.click_element('Кнопка Сохранить в создании тура продавца')
        page.wait_for_timeout(1000)
        assertions.check_create_tour_in_db_with_genre( db_connection, SELLER_TOUR_TITLE1,2,7)
        createtour.click_element('1й жанр в параметрах тура')
        createtour.click_element('3й жанр в параметрах тура')
        createtour.click_element('Кнопка Сохранить в создании тура продавца')
        assertions.verify_checkbox_state(page, '1й жанр в параметрах тура', False)
        assertions.verify_checkbox_state(page, '3й жанр в параметрах тура', False)
        assertions.check_svg_near_text('Жанры')
        createtour.click_element('2й жанр в параметрах тура')
        createtour.click_element('4й жанр в параметрах тура')
        assertions.verify_checkbox_state(page, '2й жанр в параметрах тура', True)
        assertions.verify_checkbox_state(page, '4й жанр в параметрах тура', True)   
        assertions.check_img_near_text('Жанры')
        createtour.click_element('Кнопка Сохранить в создании тура продавца')
        page.wait_for_timeout(1000)
        assertions.check_create_tour_in_db_with_genre( db_connection, SELLER_TOUR_TITLE1,4,16)       
        assertions.check_operator_tour_param_button_on_review_inactive()
        assertions.check_request_statuses(intercept_requests)
        createtour.delete_tour_in_db(db_connection, db_connection_dev_logs, SELLER_TOUR_TITLE1)


    @allure.title('Создание тура. Выбор класса')
    def test_seller_create_tour6 (self, page: Page, intercept_requests, db_connection, db_connection_dev_logs):
        createtour = SellerCreateUpdateTour(page)
        assertions = AssertionsTourParametrs(page)
        createtour.delete_tour_in_db(db_connection, db_connection_dev_logs, SELLER_TOUR_TITLE1)
        createtour.seller_goto_create_tour_old(page, SELLER_LOGIN4_TOURS, SELLER_PASSWORD1)
        assertions.check_operator_tour_param_button_create_inactive()
        assertions.check_svg_near_text('Основное')
        assertions.check_create_tour_all_fields_disable(SELLER_TOUR_CLASS_DISABLE)
        assertions.check_operator_tour_create_status_front( page, SELLER_TOUR_STATUS1_NO_SAVE )
        createtour.seller_create_tour_fill_general(page, SELLER_TOUR_TITLE1)
        assertions.check_operator_tour_param_button_create_active()
        assertions.check_img_near_text('Основное')
        assertions.check_create_tour_in_db( db_connection, SELLER_TOUR_TITLE1, 1, 6, 1, SELLER_TOUR_TITLE1_SLUG, 717)
        assertions.verify_classes_by_xpath(page, False,False,False)
        assertions.check_svg_near_text('Класс обслуживания')
        createtour.click_element('1й класс в параметрах тура')
        createtour.click_element('Кнопка Сохранить в создании тура продавца')
        page.wait_for_timeout(1000)
        assertions.check_img_near_text('Класс обслуживания')
        assertions.verify_classes_by_xpath(page, True,False,False)
        assertions.check_create_tour_in_db_with_class(db_connection, SELLER_TOUR_TITLE1, 1)
        createtour.click_element('2й класс в параметрах тура')
        createtour.click_element('Кнопка Сохранить в создании тура продавца')
        page.wait_for_timeout(1000)
        assertions.verify_classes_by_xpath(page, False,True,False)
        assertions.check_create_tour_in_db_with_class(db_connection, SELLER_TOUR_TITLE1, 2)
        assertions.check_operator_tour_param_button_on_review_inactive()
        assertions.check_request_statuses(intercept_requests)
        createtour.delete_tour_in_db(db_connection, db_connection_dev_logs, SELLER_TOUR_TITLE1)


    @allure.title('Создание тура. Выбор транспорта')
    def test_seller_create_tour7 (self, page: Page, intercept_requests, db_connection, db_connection_dev_logs):
        createtour = SellerCreateUpdateTour(page)
        assertions = AssertionsTourParametrs(page)
        createtour.delete_tour_in_db(db_connection, db_connection_dev_logs, SELLER_TOUR_TITLE1)
        createtour.seller_goto_create_tour_old(page, SELLER_LOGIN4_TOURS, SELLER_PASSWORD1)
        assertions.check_operator_tour_param_button_create_inactive()
        assertions.check_svg_near_text('Основное')
        assertions.check_create_tour_all_fields_disable(SELLER_TOUR_CLASS_DISABLE)
        assertions.check_operator_tour_create_status_front( page, SELLER_TOUR_STATUS1_NO_SAVE )
        createtour.seller_create_tour_fill_general(page, SELLER_TOUR_TITLE1)
        assertions.check_operator_tour_param_button_create_active()
        assertions.check_img_near_text('Основное')
        assertions.check_create_tour_in_db( db_connection, SELLER_TOUR_TITLE1, 1, 6, 1, SELLER_TOUR_TITLE1_SLUG, 717)
        assertions.verify_transport_front_by_xpath(page, False,False)
        assertions.check_svg_near_text('Транспорт')
        createtour.click_element('На своей машине в параметрах тура')
        createtour.click_element('Кнопка Сохранить в создании тура продавца')
        page.wait_for_timeout(1000)
        assertions.check_img_near_text('Транспорт')
        page.wait_for_timeout(2000)
        assertions.verify_transport_front_by_xpath(page, True,False)
        assertions.check_create_tour_in_db_with_transport(db_connection, SELLER_TOUR_TITLE1,1)
        createtour.click_element('На машине организатора в параметрах тура')
        createtour.click_element('Кнопка Сохранить в создании тура продавца')
        page.wait_for_timeout(1000)
        assertions.verify_transport_front_by_xpath(page, False, True)
        assertions.check_create_tour_in_db_with_transport(db_connection, SELLER_TOUR_TITLE1,2)
        assertions.check_operator_tour_param_button_on_review_inactive()
        assertions.check_request_statuses(intercept_requests)
        createtour.delete_tour_in_db(db_connection, db_connection_dev_logs, SELLER_TOUR_TITLE1)


    @allure.title('Создание тура. Загрузка фото')
    def test_seller_create_tour8(self, page: Page, intercept_requests, db_connection, photo_paths, db_connection_dev_logs):
        createtour = SellerCreateUpdateTour(page)
        assertions = AssertionsTourParametrs(page)
        createtour.delete_tour_in_db(db_connection, db_connection_dev_logs, SELLER_TOUR_TITLE1)
        createtour.seller_goto_create_tour_old(page, SELLER_LOGIN4_TOURS, SELLER_PASSWORD1)
        assertions.check_operator_tour_param_button_create_inactive()
        assertions.check_svg_near_text('Основное')
        assertions.check_create_tour_all_fields_disable(SELLER_TOUR_CLASS_DISABLE)
        assertions.check_operator_tour_create_status_front(page, SELLER_TOUR_STATUS1_NO_SAVE)
        createtour.seller_create_tour_fill_general(page, SELLER_TOUR_TITLE1)
        assertions.check_operator_tour_param_button_create_active()
        assertions.check_img_near_text('Основное')
        assertions.check_create_tour_in_db(db_connection, SELLER_TOUR_TITLE1, 1, 6, 1, SELLER_TOUR_TITLE1_SLUG, 717)
        assertions.check_svg_near_text('Фотографии')
        paths = photo_paths("1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg")
        createtour.upload_photos_via_click('Поле загрузки фото в создании тура продавца', 5, *paths)
        assertions.check_create_tour_in_db_with_photo(db_connection, SELLER_TOUR_TITLE1, 5)
        assertions.check_img_near_text('Фотографии')
        createtour.click_element('Кнопка удалить для Фото5 в создании тура продавца')
        createtour.click_element('Кнопка подтверждающая удаления фото в создании тура продавца')
        assertions.check_svg_near_text('Фотографии')
        assertions.check_create_tour_in_db_with_photo(db_connection, SELLER_TOUR_TITLE1, 4)
        assertions.check_request_statuses(intercept_requests)
        createtour.delete_tour_in_db(db_connection, db_connection_dev_logs, SELLER_TOUR_TITLE1)



    @allure.title('Создание тура. Проверка отметки раздела фото заполненным и удаления фото')
    def test_seller_create_tour9(self, page: Page, intercept_requests, db_connection, photo_paths, db_connection_dev_logs):
        createtour = SellerCreateUpdateTour(page)
        assertions = AssertionsTourParametrs(page)
        createtour.delete_tour_in_db(db_connection, db_connection_dev_logs, SELLER_TOUR_TITLE1)
        createtour.seller_goto_create_tour_old(page, SELLER_LOGIN4_TOURS, SELLER_PASSWORD1)
        assertions.check_operator_tour_param_button_create_inactive()
        assertions.check_svg_near_text('Основное')
        assertions.check_create_tour_all_fields_disable(SELLER_TOUR_CLASS_DISABLE)
        assertions.check_operator_tour_create_status_front(page, SELLER_TOUR_STATUS1_NO_SAVE)
        createtour.seller_create_tour_fill_general(page, SELLER_TOUR_TITLE1)
        assertions.check_operator_tour_param_button_create_active()
        assertions.check_img_near_text('Основное')
        assertions.check_create_tour_in_db(db_connection, SELLER_TOUR_TITLE1, 1, 6, 1, SELLER_TOUR_TITLE1_SLUG, 717)    
        assertions.check_svg_near_text('Фотографии')
        paths = photo_paths("1.jpg")
        createtour.upload_photos_via_click('Поле загрузки фото в создании тура продавца', 1, *paths)
        assertions.check_create_tour_in_db_with_photo(db_connection, SELLER_TOUR_TITLE1, 1)
        assertions.check_svg_near_text('Фотографии')
        paths = photo_paths("2.jpg")
        createtour.upload_photos_via_click('Поле загрузки фото в создании тура продавца', 2, *paths)
        assertions.check_create_tour_in_db_with_photo(db_connection, SELLER_TOUR_TITLE1, 2)
        assertions.check_svg_near_text('Фотографии')
        paths = photo_paths("3.jpg")
        createtour.upload_photos_via_click('Поле загрузки фото в создании тура продавца', 3, *paths)
        assertions.check_create_tour_in_db_with_photo(db_connection, SELLER_TOUR_TITLE1, 3)
        assertions.check_svg_near_text('Фотографии')
        paths = photo_paths("4.jpg")
        createtour.upload_photos_via_click('Поле загрузки фото в создании тура продавца', 4, *paths)
        assertions.check_create_tour_in_db_with_photo(db_connection, SELLER_TOUR_TITLE1, 4)
        assertions.check_svg_near_text('Фотографии')
        paths = photo_paths("5.jpg")
        createtour.upload_photos_via_click('Поле загрузки фото в создании тура продавца', 5, *paths)
        assertions.check_create_tour_in_db_with_photo(db_connection, SELLER_TOUR_TITLE1, 5)
        assertions.check_img_near_text('Фотографии')
        paths = photo_paths("6.jpg")
        createtour.upload_photos_via_click('Поле загрузки фото в создании тура продавца', 6, *paths)
        assertions.check_create_tour_in_db_with_photo(db_connection, SELLER_TOUR_TITLE1, 6)
        assertions.check_img_near_text('Фотографии')
        paths = photo_paths("7.jpg")
        createtour.upload_photos_via_click('Поле загрузки фото в создании тура продавца', 7, *paths)
        assertions.check_create_tour_in_db_with_photo(db_connection, SELLER_TOUR_TITLE1, 7)
        assertions.check_img_near_text('Фотографии')
        paths = photo_paths("8.jpg")
        createtour.upload_photos_via_click('Поле загрузки фото в создании тура продавца', 8, *paths)
        assertions.check_create_tour_in_db_with_photo(db_connection, SELLER_TOUR_TITLE1, 8)
        assertions.check_img_near_text('Фотографии')
        paths = photo_paths("9.jpg")
        createtour.upload_photos_via_click('Поле загрузки фото в создании тура продавца', 9, *paths)
        assertions.check_create_tour_in_db_with_photo(db_connection, SELLER_TOUR_TITLE1, 9)
        assertions.check_img_near_text('Фотографии')
        paths = photo_paths("10.jpg")
        createtour.upload_photos_via_click('Поле загрузки фото в создании тура продавца', 10, *paths)
        assertions.check_create_tour_in_db_with_photo(db_connection, SELLER_TOUR_TITLE1, 10)
        assertions.check_img_near_text('Фотографии')
        createtour.click_element('Кнопка удалить для Фото10 в создании тура продавца')
        createtour.click_element('Кнопка подтверждающая удаления фото в создании тура продавца')
        page.wait_for_timeout(1000)
        assertions.check_create_tour_in_db_with_photo(db_connection, SELLER_TOUR_TITLE1, 9)
        assertions.check_img_near_text('Фотографии')
        createtour.click_element('Кнопка удалить для Фото9 в создании тура продавца')
        createtour.click_element('Кнопка подтверждающая удаления фото в создании тура продавца')
        page.wait_for_timeout(1000)
        assertions.check_create_tour_in_db_with_photo(db_connection, SELLER_TOUR_TITLE1, 8)
        assertions.check_img_near_text('Фотографии')
        createtour.click_element('Кнопка удалить для Фото8 в создании тура продавца')
        createtour.click_element('Кнопка подтверждающая удаления фото в создании тура продавца')
        page.wait_for_timeout(1000)
        assertions.check_create_tour_in_db_with_photo(db_connection, SELLER_TOUR_TITLE1, 7)
        assertions.check_img_near_text('Фотографии')
        createtour.click_element('Кнопка удалить для Фото7 в создании тура продавца')
        createtour.click_element('Кнопка подтверждающая удаления фото в создании тура продавца')
        page.wait_for_timeout(1000)
        assertions.check_create_tour_in_db_with_photo(db_connection, SELLER_TOUR_TITLE1, 6)
        assertions.check_img_near_text('Фотографии')
        createtour.click_element('Кнопка удалить для Фото6 в создании тура продавца')
        createtour.click_element('Кнопка подтверждающая удаления фото в создании тура продавца')
        page.wait_for_timeout(1000)
        assertions.check_create_tour_in_db_with_photo(db_connection, SELLER_TOUR_TITLE1, 5)
        assertions.check_img_near_text('Фотографии')
        createtour.click_element('Кнопка удалить для Фото5 в создании тура продавца')
        createtour.click_element('Кнопка подтверждающая удаления фото в создании тура продавца')
        page.wait_for_timeout(1000)
        assertions.check_create_tour_in_db_with_photo(db_connection, SELLER_TOUR_TITLE1, 4)
        assertions.check_svg_near_text('Фотографии')
        createtour.click_element('Кнопка удалить для Фото4 в создании тура продавца')
        createtour.click_element('Кнопка подтверждающая удаления фото в создании тура продавца')
        page.wait_for_timeout(1000)
        assertions.check_create_tour_in_db_with_photo(db_connection, SELLER_TOUR_TITLE1, 3)
        assertions.check_svg_near_text('Фотографии')
        createtour.click_element('Кнопка удалить для Фото3 в создании тура продавца')
        createtour.click_element('Кнопка подтверждающая удаления фото в создании тура продавца')
        page.wait_for_timeout(1000)
        assertions.check_create_tour_in_db_with_photo(db_connection, SELLER_TOUR_TITLE1, 2)
        assertions.check_svg_near_text('Фотографии')
        createtour.click_element('Кнопка удалить для Фото2 в создании тура продавца')
        createtour.click_element('Кнопка подтверждающая удаления фото в создании тура продавца')
        page.wait_for_timeout(1000)
        assertions.check_create_tour_in_db_with_photo(db_connection, SELLER_TOUR_TITLE1, 1)
        assertions.check_svg_near_text('Фотографии')
        createtour.click_element('Кнопка удалить для Фото1 в создании тура продавца')
        createtour.click_element('Кнопка подтверждающая удаления фото в создании тура продавца')
        page.wait_for_timeout(1000)
        assertions.check_create_tour_in_db_with_photo(db_connection, SELLER_TOUR_TITLE1, 0)
        assertions.check_svg_near_text('Фотографии')
        assertions.check_request_statuses(intercept_requests)
        createtour.delete_tour_in_db(db_connection, db_connection_dev_logs, SELLER_TOUR_TITLE1)


    @allure.title('Создание тура. Проверка предупреждения, если больше 10 фото')
    def test_seller_create_tour10(self, page: Page, intercept_requests, db_connection, photo_paths, db_connection_dev_logs):
        createtour = SellerCreateUpdateTour(page)
        assertions = AssertionsTourParametrs(page)
        createtour.delete_tour_in_db(db_connection, db_connection_dev_logs, SELLER_TOUR_TITLE1)
        createtour.seller_goto_create_tour_old(page, SELLER_LOGIN4_TOURS, SELLER_PASSWORD1)
        assertions.check_operator_tour_param_button_create_inactive()
        assertions.check_svg_near_text('Основное')
        assertions.check_create_tour_all_fields_disable(SELLER_TOUR_CLASS_DISABLE)
        assertions.check_operator_tour_create_status_front(page, SELLER_TOUR_STATUS1_NO_SAVE)
        createtour.seller_create_tour_fill_general(page, SELLER_TOUR_TITLE1)
        assertions.check_operator_tour_param_button_create_active()
        assertions.check_img_near_text('Основное')
        assertions.check_create_tour_in_db(db_connection, SELLER_TOUR_TITLE1, 1, 6, 1, SELLER_TOUR_TITLE1_SLUG, 717)    
        assertions.check_svg_near_text('Фотографии')
        paths = photo_paths("1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg", "7.jpg", "8.jpg", "9.jpg", "10.jpg", "11.jpg")
        createtour.upload_photos_via_click('Поле загрузки фото в создании тура продавца', 10, *paths)
        assertions.check_create_tour_in_db_with_photo(db_connection, SELLER_TOUR_TITLE1, 10)
        assertions.check_photo_count_warning_visible()
        assertions.check_img_near_text('Фотографии')
        assertions.check_request_statuses(intercept_requests)
        createtour.delete_tour_in_db(db_connection, db_connection_dev_logs, SELLER_TOUR_TITLE1)

    @allure.title('Создание тура. Проверка выбора главного фото')
    def test_seller_create_tour11(self, page: Page, intercept_requests, db_connection, photo_paths, db_connection_dev_logs):
        createtour = SellerCreateUpdateTour(page)
        assertions = AssertionsTourParametrs(page)
        createtour.delete_tour_in_db(db_connection, db_connection_dev_logs, SELLER_TOUR_TITLE1)
        createtour.seller_goto_create_tour_old(page, SELLER_LOGIN4_TOURS, SELLER_PASSWORD1)
        assertions.check_operator_tour_param_button_create_inactive()
        assertions.check_svg_near_text('Основное')
        assertions.check_create_tour_all_fields_disable(SELLER_TOUR_CLASS_DISABLE)
        assertions.check_operator_tour_create_status_front(page, SELLER_TOUR_STATUS1_NO_SAVE)
        createtour.seller_create_tour_fill_general(page, SELLER_TOUR_TITLE1)
        assertions.check_operator_tour_param_button_create_active()
        assertions.check_img_near_text('Основное')
        assertions.check_create_tour_in_db(db_connection, SELLER_TOUR_TITLE1, 1, 6, 1, SELLER_TOUR_TITLE1_SLUG, 717)    
        assertions.check_svg_near_text('Фотографии')
        paths = photo_paths("1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg", "7.jpg", "8.jpg", "9.jpg", "10.jpg")
        createtour.upload_photos_via_click('Поле загрузки фото в создании тура продавца', 10, *paths)
        assertions.check_create_tour_in_db_with_photo(db_connection, SELLER_TOUR_TITLE1, 10)
        assertions.check_img_near_text('Фотографии')
        assertions.check_main_photo_marked(1)
        createtour.hover_element('Выбор 2го фото главным в создании тура продавца')
        createtour.click_element('Выбор 2го фото главным в создании тура продавца')
        assertions.check_main_photo_marked(2)
        createtour.click_element('Кнопка удалить для Фото2 в создании тура продавца')
        createtour.click_element('Кнопка подтверждающая удаления фото в создании тура продавца')
        assertions.check_main_photo_marked(1)  
        createtour.hover_element('Выбор 6го фото главным в создании тура продавца')
        createtour.click_element('Выбор 6го фото главным в создании тура продавца')
        assertions.check_main_photo_marked(6)
        assertions.check_request_statuses(intercept_requests)
        createtour.delete_tour_in_db(db_connection, db_connection_dev_logs, SELLER_TOUR_TITLE1)


    @allure.title('Создание тура. Сохранение описания')
    def test_seller_create_tour12(self, page: Page, intercept_requests, db_connection, photo_paths, db_connection_dev_logs):
        createtour = SellerCreateUpdateTour(page)
        assertions = AssertionsTourParametrs(page)
        createtour.delete_tour_in_db(db_connection, db_connection_dev_logs, SELLER_TOUR_TITLE1)
        createtour.seller_goto_create_tour_old(page, SELLER_LOGIN4_TOURS, SELLER_PASSWORD1)
        assertions.check_operator_tour_param_button_create_inactive()
        assertions.check_svg_near_text('Основное')
        assertions.check_create_tour_all_fields_disable(SELLER_TOUR_CLASS_DISABLE)
        assertions.check_operator_tour_create_status_front(page, SELLER_TOUR_STATUS1_NO_SAVE)
        createtour.seller_create_tour_fill_general(page, SELLER_TOUR_TITLE1)
        assertions.check_operator_tour_param_button_create_active()
        assertions.check_img_near_text('Основное')
        assertions.check_create_tour_in_db(db_connection, SELLER_TOUR_TITLE1, 1, 6, 1, SELLER_TOUR_TITLE1_SLUG, 717)  
        assertions.check_svg_near_text('Описание')
        createtour.fill_element('Описание в создании тура продавца', SELLER_TOUR_DESCRIPTION1)
        createtour.click_element('Кнопка Сохранить в создании тура продавца')
        assertions.check_img_near_text('Описание')
        page.wait_for_timeout(2000)
        assertions.check_field_value_from_locator('Описание в создании тура продавца', SELLER_TOUR_DESCRIPTION1)
        assertions.check_create_tour_in_db_with_desc(db_connection, SELLER_TOUR_TITLE1, SELLER_TOUR_DESCRIPTION1_IN_DB)
        createtour.fill_element('Описание в создании тура продавца', SELLER_TOUR_DESCRIPTION2)
        createtour.click_element('Кнопка Сохранить в создании тура продавца')
        page.wait_for_timeout(2000)
        assertions.check_field_value_from_locator('Описание в создании тура продавца', SELLER_TOUR_DESCRIPTION2)
        assertions.check_create_tour_in_db_with_desc(db_connection, SELLER_TOUR_TITLE1, SELLER_TOUR_DESCRIPTION2_IN_DB)       
        assertions.check_request_statuses(intercept_requests)
        createtour.delete_tour_in_db(db_connection, db_connection_dev_logs, SELLER_TOUR_TITLE1)


    @allure.title('Создание тура. Сохранение Что входит')
    def test_seller_create_tour13(self, page: Page, intercept_requests, db_connection, photo_paths, db_connection_dev_logs):
        createtour = SellerCreateUpdateTour(page)
        assertions = AssertionsTourParametrs(page)
        createtour.delete_tour_in_db(db_connection, db_connection_dev_logs, SELLER_TOUR_TITLE1)
        createtour.seller_goto_create_tour_old(page, SELLER_LOGIN4_TOURS, SELLER_PASSWORD1)
        assertions.check_operator_tour_param_button_create_inactive()
        assertions.check_svg_near_text('Основное')
        assertions.check_create_tour_all_fields_disable(SELLER_TOUR_CLASS_DISABLE)
        assertions.check_operator_tour_create_status_front(page, SELLER_TOUR_STATUS1_NO_SAVE)
        createtour.seller_create_tour_fill_general(page, SELLER_TOUR_TITLE1)
        assertions.check_operator_tour_param_button_create_active()
        assertions.check_img_near_text('Основное')
        assertions.check_create_tour_in_db(db_connection, SELLER_TOUR_TITLE1, 1, 6, 1, SELLER_TOUR_TITLE1_SLUG, 717) 
        assertions.check_svg_near_text('Что входит в стоимость')
        createtour.fill_element('Что входит в стоимость в создании тура продавца', SELLER_TOUR_INPRICE1)
        createtour.click_element('Кнопка Сохранить в создании тура продавца')
        assertions.check_img_near_text('Что входит в стоимость')
        page.wait_for_timeout(2000)
        assertions.check_field_value_from_locator('Что входит в стоимость в создании тура продавца', SELLER_TOUR_INPRICE1)
        assertions.check_create_tour_in_db_with_in_price(db_connection, SELLER_TOUR_TITLE1, SELLER_TOUR_INPRICE1_IN_DB)
        createtour.fill_element('Что входит в стоимость в создании тура продавца', SELLER_TOUR_INPRICE2)
        createtour.click_element('Кнопка Сохранить в создании тура продавца')
        page.wait_for_timeout(2000)
        assertions.check_field_value_from_locator('Что входит в стоимость в создании тура продавца', SELLER_TOUR_INPRICE2)
        assertions.check_create_tour_in_db_with_in_price(db_connection, SELLER_TOUR_TITLE1, SELLER_TOUR_INPRICE2_IN_DB)       
        assertions.check_request_statuses(intercept_requests)
        createtour.delete_tour_in_db(db_connection, db_connection_dev_logs, SELLER_TOUR_TITLE1)


    @allure.title('Создание тура. Сохранение Что не входит')
    def test_seller_create_tour14(self, page: Page, intercept_requests, db_connection, photo_paths, db_connection_dev_logs):
        createtour = SellerCreateUpdateTour(page)
        assertions = AssertionsTourParametrs(page)
        createtour.delete_tour_in_db(db_connection, db_connection_dev_logs, SELLER_TOUR_TITLE1)
        createtour.seller_goto_create_tour_old(page, SELLER_LOGIN4_TOURS, SELLER_PASSWORD1)
        assertions.check_operator_tour_param_button_create_inactive()
        assertions.check_svg_near_text('Основное')
        assertions.check_create_tour_all_fields_disable(SELLER_TOUR_CLASS_DISABLE)
        assertions.check_operator_tour_create_status_front(page, SELLER_TOUR_STATUS1_NO_SAVE)
        createtour.seller_create_tour_fill_general(page, SELLER_TOUR_TITLE1)
        assertions.check_operator_tour_param_button_create_active()
        assertions.check_img_near_text('Основное')
        assertions.check_create_tour_in_db(db_connection, SELLER_TOUR_TITLE1, 1, 6, 1, SELLER_TOUR_TITLE1_SLUG, 717) 
        createtour.fill_element('Что не входит в стоимость в создании тура продавца', SELLER_TOUR_NOT_IN_INPRICE1)
        createtour.click_element('Кнопка Сохранить в создании тура продавца')
        page.wait_for_timeout(2000)
        assertions.check_field_value_from_locator('Что не входит в стоимость в создании тура продавца', SELLER_TOUR_NOT_IN_INPRICE1)
        assertions.check_create_tour_in_db_with_not_in_price(db_connection, SELLER_TOUR_TITLE1, SELLER_TOUR_NOT_IN_INPRICE1_IN_DB)
        createtour.fill_element('Что не входит в стоимость в создании тура продавца', SELLER_TOUR_NOT_IN_INPRICE2)
        createtour.click_element('Кнопка Сохранить в создании тура продавца')
        page.wait_for_timeout(2000)
        assertions.check_field_value_from_locator('Что не входит в стоимость в создании тура продавца', SELLER_TOUR_NOT_IN_INPRICE2)
        assertions.check_create_tour_in_db_with_not_in_price(db_connection, SELLER_TOUR_TITLE1, SELLER_TOUR_NOT_IN_INPRICE2_IN_DB)       
        assertions.check_request_statuses(intercept_requests)
        createtour.delete_tour_in_db(db_connection, db_connection_dev_logs, SELLER_TOUR_TITLE1)


    @allure.title('Создание тура. Сохранение Кому подойдет')
    def test_seller_create_tour15(self, page: Page, intercept_requests, db_connection, photo_paths, db_connection_dev_logs):
        createtour = SellerCreateUpdateTour(page)
        assertions = AssertionsTourParametrs(page)
        createtour.delete_tour_in_db(db_connection, db_connection_dev_logs, SELLER_TOUR_TITLE1)
        createtour.seller_goto_create_tour_old(page, SELLER_LOGIN4_TOURS, SELLER_PASSWORD1)
        assertions.check_operator_tour_param_button_create_inactive()
        assertions.check_svg_near_text('Основное')
        assertions.check_create_tour_all_fields_disable(SELLER_TOUR_CLASS_DISABLE)
        assertions.check_operator_tour_create_status_front(page, SELLER_TOUR_STATUS1_NO_SAVE)
        createtour.seller_create_tour_fill_general(page, SELLER_TOUR_TITLE1)
        assertions.check_operator_tour_param_button_create_active()
        assertions.check_img_near_text('Основное')
        assertions.check_create_tour_in_db(db_connection, SELLER_TOUR_TITLE1, 1, 6, 1, SELLER_TOUR_TITLE1_SLUG, 717) 
        assertions.check_svg_near_text('Кому подойдёт')
        createtour.click_element('Кому подойдет1 в создании тура продавца')
        assertions.verify_toggle_checked_by_xpath(page,'Кому подойдет1 в создании тура продавца', 'true')
        assertions.check_img_near_text('Кому подойдёт')
        createtour.click_element('Кому подойдет2 в создании тура продавца')
        page.wait_for_timeout(500)
        assertions.verify_toggle_checked_by_xpath(page,'Кому подойдет2 в создании тура продавца', 'true')
        createtour.click_element('Кнопка Сохранить в создании тура продавца')
        page.wait_for_timeout(2000)
        assertions.check_create_tour_in_db_with_suitable(db_connection, SELLER_TOUR_TITLE1, 4, 5)
        createtour.click_element('Кому подойдет1 в создании тура продавца')
        page.wait_for_timeout(500)
        assertions.verify_toggle_checked_by_xpath(page,'Кому подойдет1 в создании тура продавца', 'false')
        createtour.click_element('Кому подойдет2 в создании тура продавца')
        page.wait_for_timeout(500)
        assertions.verify_toggle_checked_by_xpath(page,'Кому подойдет2 в создании тура продавца', 'false')
        assertions.check_svg_near_text('Кому подойдёт')
        createtour.click_element('Кому подойдет3 в создании тура продавца')
        page.wait_for_timeout(500)
        assertions.verify_toggle_checked_by_xpath(page,'Кому подойдет3 в создании тура продавца', 'true')
        assertions.check_img_near_text('Кому подойдёт')
        createtour.click_element('Кому подойдет4 в создании тура продавца')
        page.wait_for_timeout(500)
        assertions.verify_toggle_checked_by_xpath(page,'Кому подойдет4 в создании тура продавца', 'true')
        createtour.click_element('Кнопка Сохранить в создании тура продавца')
        page.wait_for_timeout(2000)
        assertions.check_create_tour_in_db_with_suitable(db_connection, SELLER_TOUR_TITLE1, 1, 3)       
        assertions.check_request_statuses(intercept_requests)
        createtour.delete_tour_in_db(db_connection, db_connection_dev_logs, SELLER_TOUR_TITLE1)


    @allure.title('Создание тура. Часовой пояс')
    def test_seller_create_tour16(self, page: Page, intercept_requests, db_connection, db_connection_dev_logs):
        createtour = SellerCreateUpdateTourWaypoints(page)
        assertions = AssertionsTourWaypoints(page)
        createtour.delete_tour_in_db(db_connection, db_connection_dev_logs, SELLER_TOUR_TITLE1)
        createtour.seller_goto_create_tour_waypoints_old(page)
        assertions.check_tour_timezone_in_db(db_connection,  SELLER_TOUR_TITLE1, 2)
        page.wait_for_timeout(2000)
        assertions.check_field_value_from_locator('Часовой пояс маршрута в создании тура продавца', SELLER_TOUR_ROUTE_TIMEZONE3)
        createtour.click_element('Крестик в маршруте в создании тура продавца')
        page.wait_for_timeout(2000)
        assertions.check_field_value_from_locator('Часовой пояс в создании тура продавца', SELLER_TOUR_TIMEZONE3)
        createtour.click_element('Кнопка Настроить маршрут в создании тура продавца')
        createtour.click_element('Часовой пояс маршрута в создании тура продавца')
        createtour.click_element('Первый часовой пояс')
        page.wait_for_timeout(1000)
        assertions.check_field_value_from_locator('Часовой пояс маршрута в создании тура продавца', SELLER_TOUR_ROUTE_TIMEZONE4)
        assertions.check_tour_timezone_in_db(db_connection,  SELLER_TOUR_TITLE1, 3)
        createtour.click_element('Крестик в маршруте в создании тура продавца')
        page.wait_for_timeout(2000)
        assertions.check_field_value_from_locator('Часовой пояс в создании тура продавца',  SELLER_TOUR_TIMEZONE4)
        assertions.check_request_statuses(intercept_requests)
        createtour.delete_tour_in_db(db_connection, db_connection_dev_logs, SELLER_TOUR_TITLE1)

    # СОЗДАНИЕ ТОЧЕК ИЗМЕНИЛИ, ЗАМЕТКИ И ВРЕМЯ ОКОНЧАНИЯ
    # @allure.title('Создание тура. Точка сбора')
    # def test_seller_create_tour17(self, page: Page, intercept_requests, db_connection, photo_paths, db_connection_dev_logs):
    #     createtour = SellerCreateUpdateTourWaypoints(page)
    #     assertions = AssertionsTourWaypoints(page)
    #     createtour.delete_tour_in_db(db_connection, db_connection_dev_logs, SELLER_TOUR_TITLE1)
    #     createtour.seller_goto_create_tour_waypoints_old(page)
    #     createtour.click_element('Точка сбора в маршруте в создании тура продавца')
    #     assertions.check_seller_waypoint_collection_point_button_save_inactive()
    #     assertions.check_element_has_class('День в точке сбора в создании тура продавца', SELLER_TOUR_ROUTE_COLLECTION_POINT_DAY_CLASS_DISABLED)  
    #     createtour.fill_element('Адрес в точке сбора в создании тура продавца', SELLER_TOUR_ROUTE_COLLECTION_POINT_ADDRESS1) # Лишнее. Из-за бага
    #     page.wait_for_timeout(1000) # Лишнее. Из-за бага
    #     createtour.fill_element('Адрес в точке сбора в создании тура продавца', SELLER_TOUR_ROUTE_COLLECTION_POINT_ADDRESS2)
    #     createtour.click_element('Первый предложенный адрес в точке сбора в создании тура продавца')
    #     page.wait_for_timeout(1000)
    #     assertions.check_field_value_from_locator('Координаты в точке сбора в создании тура продавца', SELLER_TOUR_ROUTE_COLLECTION_POINT_CORDS1)
    #     assertions.check_field_value_from_locator('Значение дня в точке сбора в создании тура продавца', SELLER_TOUR_ROUTE_COLLECTION_POINT_DAY1)
    #     createtour.fill_element('Время в точке сбора в создании тура продавца', SELLER_TOUR_ROUTE_COLLECTION_POINT_TIME1)
    #     createtour.fill_element('Название в точке сбора в создании тура продавца', SELLER_TOUR_ROUTE_COLLECTION_POINT_TITLE1)
    #     createtour.fill_element('Описание в точке сбора в создании тура продавца', SELLER_TOUR_ROUTE_COLLECTION_POINT_DESCRIPTION1)
    #     paths = photo_paths("1.jpg")
    #     createtour.upload_photos_via_click_general('Загрузка фото в точке сбора в создании тура продавца ', 1, *paths)
    #     createtour.click_element('Кнопка Сохранить в точке сбора в создании тура продавца')
    #     page.wait_for_timeout(3000)
    #     assertions.check_seller_waypoint_in_db(db_connection, SELLER_TOUR_TITLE1,
    #                                             SELLER_TOUR_ROUTE_COLLECTION_POINT_CORDS1_IN_DB,
    #                                             SELLER_TOUR_ROUTE_COLLECTION_POINT_TIME1_IN_DB,
    #                                             SELLER_TOUR_ROUTE_COLLECTION_POINT_TITLE1,
    #                                             SELLER_TOUR_ROUTE_COLLECTION_POINT_DESCRIPTION1_IN_DB,
    #                                             1,
    #                                             1
    #                                             )
    #     createtour.click_element('Крестик в маршруте в создании тура продавца')
    #     assertions.check_img_near_text('Маршрут')
    #     createtour.click_element('Кнопка Настроить маршрут в создании тура продавца')
    #     createtour.click_element('Точка сбора в маршруте в создании тура продавца')
    #     createtour.fill_element('Адрес в точке сбора в создании тура продавца', '')
    #     createtour.fill_element('Адрес в точке сбора в создании тура продавца', SELLER_TOUR_ROUTE_COLLECTION_POINT_ADDRESS2) # Лишнее. Из-за бага
    #     page.wait_for_timeout(1000) # Лишнее. Из-за бага
    #     createtour.fill_element('Адрес в точке сбора в создании тура продавца', SELLER_TOUR_ROUTE_COLLECTION_POINT_ADDRESS1)
    #     createtour.click_element('Первый предложенный адрес в точке сбора в создании тура продавца')
    #     page.wait_for_timeout(1000)
    #     assertions.check_field_value_from_locator('Координаты в точке сбора в создании тура продавца', SELLER_TOUR_ROUTE_COLLECTION_POINT_CORDS2)
    #     assertions.check_field_value_from_locator('Значение дня в точке сбора в создании тура продавца', SELLER_TOUR_ROUTE_COLLECTION_POINT_DAY1)
    #     createtour.fill_element('Время в точке сбора в создании тура продавца', SELLER_TOUR_ROUTE_COLLECTION_POINT_TIME2)
    #     createtour.fill_element('Название в точке сбора в создании тура продавца', SELLER_TOUR_ROUTE_COLLECTION_POINT_TITLE2)
    #     createtour.fill_element('Описание в точке сбора в создании тура продавца', SELLER_TOUR_ROUTE_COLLECTION_POINT_DESCRIPTION2)
    #     paths = photo_paths("2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg",)
    #     createtour.upload_photos_via_click_general('Загрузка фото в точке сбора в создании тура продавца ', 5, *paths)
    #     createtour.click_element('Кнопка Сохранить в точке сбора в создании тура продавца')
    #     page.wait_for_timeout(3000)
    #     assertions.check_seller_waypoint_in_db(db_connection, SELLER_TOUR_TITLE1,
    #                                             SELLER_TOUR_ROUTE_COLLECTION_POINT_CORDS2_IN_DB,
    #                                             SELLER_TOUR_ROUTE_COLLECTION_POINT_TIME2_IN_DB,
    #                                             SELLER_TOUR_ROUTE_COLLECTION_POINT_TITLE2,
    #                                             SELLER_TOUR_ROUTE_COLLECTION_POINT_DESCRIPTION2_IN_DB,
    #                                             5,
    #                                             1
    #                                             )
    #     assertions.check_request_statuses(intercept_requests)
    #     createtour.delete_tour_in_db(db_connection, db_connection_dev_logs, SELLER_TOUR_TITLE1)

    @allure.title('Создание тура. HotelID')
    def test_seller_create_tour18(self, page: Page, intercept_requests, db_connection, photo_paths, db_connection_dev_logs):
        createtour = SellerCreateUpdateTour(page)
        assertions = AssertionsTourParametrs(page)
        createtour.delete_tour_in_db(db_connection, db_connection_dev_logs, SELLER_TOUR_TITLE1)
        createtour.seller_goto_create_tour_old(page, SELLER_LOGIN4_TOURS, SELLER_PASSWORD1)
        assertions.check_operator_tour_param_button_create_inactive()
        assertions.check_svg_near_text('Основное')
        assertions.check_create_tour_all_fields_disable(SELLER_TOUR_CLASS_DISABLE)
        assertions.check_operator_tour_create_status_front(page, SELLER_TOUR_STATUS1_NO_SAVE)
        createtour.seller_create_tour_fill_general(page, SELLER_TOUR_TITLE1)
        assertions.check_operator_tour_param_button_create_active()
        assertions.check_img_near_text('Основное')
        page.wait_for_timeout(1000)
        assertions.check_create_tour_in_db(db_connection, SELLER_TOUR_TITLE1, 1, 6, 1, SELLER_TOUR_TITLE1_SLUG, 717) 
        assertions.check_svg_near_text('Идентификатор отеля')
        createtour.fill_element('HotelID в создании тура продавца', SELLER_TOUR_HOTELID)
        createtour.fill_element('Ссылка на HotelID в создании тура продавца', SELLER_TOUR_HOTELID_LINK)
        createtour.click_element('Кнопка Сохранить в создании тура продавца')
        page.wait_for_timeout(2000)
        assertions.check_field_value_from_locator('HotelID в создании тура продавца', SELLER_TOUR_HOTELID)
        assertions.check_field_value_from_locator('Ссылка на HotelID в создании тура продавца', SELLER_TOUR_HOTELID_LINK)
        # assertions.check_create_tour_in_db_with_hotelid(db_connection, SELLER_TOUR_TITLE1, SELLER_TOUR_HOTELID, SELLER_TOUR_HOTELID_LINK)
        createtour.fill_element('HotelID в создании тура продавца', SELLER_TOUR_HOTELID2)
        createtour.fill_element('Ссылка на HotelID в создании тура продавца', SELLER_TOUR_HOTELID_LINK2)
        createtour.click_element('Кнопка Сохранить в создании тура продавца')
        # assertions.check_img_near_text('Идентификатор отеля')
        page.wait_for_timeout(2000)
        assertions.check_field_value_from_locator('HotelID в создании тура продавца', SELLER_TOUR_HOTELID2)
        assertions.check_field_value_from_locator('Ссылка на HotelID в создании тура продавца', SELLER_TOUR_HOTELID_LINK2)
        # assertions.check_create_tour_in_db_with_hotelid(db_connection, SELLER_TOUR_TITLE1, SELLER_TOUR_HOTELID2, SELLER_TOUR_HOTELID_LINK2)    
        assertions.check_request_statuses(intercept_requests)
        createtour.delete_tour_in_db(db_connection, db_connection_dev_logs, SELLER_TOUR_TITLE1)


    @allure.title('Создание тура и отправка на модерацию')
    def test_seller_create_tour19 (self, page: Page, intercept_requests, db_connection, photo_paths, db_connection_dev_logs):
        createtour = SellerCreateUpdateTourWaypoints(page)
        assertions = AssertionsTourWaypoints(page)
        createtour.delete_tour_in_db(db_connection, db_connection_dev_logs, SELLER_TOUR_TITLE1)
        createtour.seller_goto_create_tour_old(page, SELLER_LOGIN4_TOURS, SELLER_PASSWORD1)
        assertions.check_operator_tour_param_button_create_inactive()
        assertions.check_svg_near_text('Основное')
        assertions.check_create_tour_all_fields_disable(SELLER_TOUR_CLASS_DISABLE)
        assertions.check_operator_tour_create_status_front( page, SELLER_TOUR_STATUS1_NO_SAVE )
        createtour.seller_create_tour_fill_general(page, SELLER_TOUR_TITLE1)
        assertions.check_operator_tour_param_button_create_active()
        assertions.check_img_near_text('Основное')
        page.wait_for_timeout(2000)
        assertions.check_create_tour_in_db( db_connection, SELLER_TOUR_TITLE1, 1, 6, 1, SELLER_TOUR_TITLE1_SLUG, 717)
        assertions.check_operator_tour_param_button_on_review_inactive()
        assertions.check_request_statuses(intercept_requests)
        assertions.check_create_tour_in_db_with_reservations(db_connection, SELLER_TOUR_TITLE1, 1, 6, 1, 717, False)
        assertions.verify_toggle_checked_by_xpath(page,'Только предварительное бронирование тогл в параметрах тура', 'false')
        createtour.click_element('Только предварительное бронирование тогл в параметрах тура')
        assertions.verify_toggle_checked_by_xpath(page,'Только предварительное бронирование тогл в параметрах тура', 'true')
        createtour.click_element('Кнопка Сохранить в создании тура продавца')
        page.wait_for_timeout(1000)
        assertions.check_create_tour_in_db_with_reservations(db_connection, SELLER_TOUR_TITLE1, 1, 6, 1, 717, True)
        assertions.check_svg_near_text('Жанры')
        assertions.verify_checkbox_state(page, '1й жанр в параметрах тура', False)
        createtour.click_element('1й жанр в параметрах тура')
        assertions.check_img_near_text('Жанры')
        assertions.verify_checkbox_state(page, '1й жанр в параметрах тура', True)
        assertions.verify_checkbox_state(page, '3й жанр в параметрах тура', False)
        createtour.click_element('3й жанр в параметрах тура')
        assertions.verify_checkbox_state(page, '3й жанр в параметрах тура', True)
        createtour.click_element('Кнопка Сохранить в создании тура продавца')
        page.wait_for_timeout(1000)
        assertions.check_create_tour_in_db_with_genre( db_connection, SELLER_TOUR_TITLE1,2,7)
        assertions.verify_classes_by_xpath(page, False,False,False)
        assertions.check_svg_near_text('Класс обслуживания')
        createtour.click_element('1й класс в параметрах тура')
        createtour.click_element('Кнопка Сохранить в создании тура продавца')
        page.wait_for_timeout(1000)
        assertions.check_img_near_text('Класс обслуживания')
        assertions.verify_classes_by_xpath(page, True,False,False)
        assertions.check_create_tour_in_db_with_class(db_connection, SELLER_TOUR_TITLE1, 1)
        assertions.verify_transport_front_by_xpath(page, False,False)
        assertions.check_svg_near_text('Транспорт')
        createtour.click_element('На своей машине в параметрах тура')
        createtour.click_element('Кнопка Сохранить в создании тура продавца')
        page.wait_for_timeout(1000)
        assertions.check_img_near_text('Транспорт')
        page.wait_for_timeout(2000)
        assertions.verify_transport_front_by_xpath(page, True,False)
        assertions.check_create_tour_in_db_with_transport(db_connection, SELLER_TOUR_TITLE1,1)
        assertions.check_svg_near_text('Фотографии')
        paths = photo_paths("1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg", "7.jpg", "8.jpg", "9.jpg", "10.jpg", "11.jpg")
        createtour.upload_photos_via_click('Поле загрузки фото в создании тура продавца', 10, *paths)
        assertions.check_create_tour_in_db_with_photo(db_connection, SELLER_TOUR_TITLE1, 10)
        assertions.check_photo_count_warning_visible()
        assertions.check_img_near_text('Фотографии')
        assertions.check_svg_near_text('Описание')
        createtour.fill_element('Описание в создании тура продавца', SELLER_TOUR_DESCRIPTION1)
        createtour.click_element('Кнопка Сохранить в создании тура продавца')
        assertions.check_img_near_text('Описание')
        page.wait_for_timeout(2000)
        assertions.check_field_value_from_locator('Описание в создании тура продавца', SELLER_TOUR_DESCRIPTION1)
        assertions.check_create_tour_in_db_with_desc(db_connection, SELLER_TOUR_TITLE1, SELLER_TOUR_DESCRIPTION1_IN_DB)
        assertions.check_svg_near_text('Что входит в стоимость')
        createtour.fill_element('Что входит в стоимость в создании тура продавца', SELLER_TOUR_INPRICE1)
        createtour.click_element('Кнопка Сохранить в создании тура продавца')
        assertions.check_img_near_text('Что входит в стоимость')
        page.wait_for_timeout(2000)
        assertions.check_field_value_from_locator('Что входит в стоимость в создании тура продавца', SELLER_TOUR_INPRICE1)
        assertions.check_create_tour_in_db_with_in_price(db_connection, SELLER_TOUR_TITLE1, SELLER_TOUR_INPRICE1_IN_DB)
        createtour.fill_element('Что не входит в стоимость в создании тура продавца', SELLER_TOUR_NOT_IN_INPRICE1)
        createtour.click_element('Кнопка Сохранить в создании тура продавца')
        page.wait_for_timeout(2000)
        assertions.check_field_value_from_locator('Что не входит в стоимость в создании тура продавца', SELLER_TOUR_NOT_IN_INPRICE1)
        assertions.check_create_tour_in_db_with_not_in_price(db_connection, SELLER_TOUR_TITLE1, SELLER_TOUR_NOT_IN_INPRICE1_IN_DB)
        createtour.fill_element('Что не входит в стоимость в создании тура продавца', SELLER_TOUR_NOT_IN_INPRICE2)
        createtour.click_element('Кнопка Сохранить в создании тура продавца')
        page.wait_for_timeout(2000)
        assertions.check_field_value_from_locator('Что не входит в стоимость в создании тура продавца', SELLER_TOUR_NOT_IN_INPRICE2)
        assertions.check_create_tour_in_db_with_not_in_price(db_connection, SELLER_TOUR_TITLE1, SELLER_TOUR_NOT_IN_INPRICE2_IN_DB)
        assertions.check_svg_near_text('Кому подойдёт')
        createtour.click_element('Кому подойдет1 в создании тура продавца')
        assertions.verify_toggle_checked_by_xpath(page,'Кому подойдет1 в создании тура продавца', 'true')
        assertions.check_img_near_text('Кому подойдёт')
        createtour.click_element('Кому подойдет2 в создании тура продавца')
        assertions.verify_toggle_checked_by_xpath(page,'Кому подойдет2 в создании тура продавца', 'true')
        createtour.click_element('Кнопка Сохранить в создании тура продавца')
        page.wait_for_timeout(2000)
        assertions.check_create_tour_in_db_with_suitable(db_connection, SELLER_TOUR_TITLE1, 4, 5)
        createtour.click_element('Кнопка Настроить маршрут в создании тура продавца')
        createtour.click_element('Точка сбора в маршруте в создании тура продавца')
        assertions.check_seller_waypoint_collection_point_button_save_inactive()
        assertions.check_element_has_class('День в точке сбора в создании тура продавца', SELLER_TOUR_ROUTE_COLLECTION_POINT_DAY_CLASS_DISABLED)
        createtour.fill_element('Адрес в точке сбора в создании тура продавца', SELLER_TOUR_ROUTE_COLLECTION_POINT_ADDRESS1) # Лишнее. Из-за бага
        page.wait_for_timeout(1000) # Лишнее. Из-за бага
        createtour.fill_element('Адрес в точке сбора в создании тура продавца', SELLER_TOUR_ROUTE_COLLECTION_POINT_ADDRESS2)
        createtour.click_element('Первый предложенный адрес в точке сбора в создании тура продавца')
        page.wait_for_timeout(1000)
        assertions.check_field_value_from_locator('Координаты в точке сбора в создании тура продавца', SELLER_TOUR_ROUTE_COLLECTION_POINT_CORDS1)
        assertions.check_field_value_from_locator('Значение дня в точке сбора в создании тура продавца', SELLER_TOUR_ROUTE_COLLECTION_POINT_DAY1)
        createtour.fill_element('Время в точке сбора в создании тура продавца', SELLER_TOUR_ROUTE_COLLECTION_POINT_TIME1)
        createtour.fill_element('Название в точке сбора в создании тура продавца', SELLER_TOUR_ROUTE_COLLECTION_POINT_TITLE1)
        createtour.fill_element('Описание в точке сбора в создании тура продавца', SELLER_TOUR_ROUTE_COLLECTION_POINT_DESCRIPTION1)
        paths = photo_paths("1.jpg")
        createtour.upload_photos_via_click_general('Загрузка фото в точке сбора в создании тура продавца ', 1, *paths)
        createtour.click_element('Кнопка Сохранить в точке сбора в создании тура продавца')
        page.wait_for_timeout(3000)
        assertions.check_seller_waypoint_in_db(db_connection, SELLER_TOUR_TITLE1,
                                                SELLER_TOUR_ROUTE_COLLECTION_POINT_CORDS1_IN_DB,
                                                SELLER_TOUR_ROUTE_COLLECTION_POINT_TIME1_IN_DB,
                                                SELLER_TOUR_ROUTE_COLLECTION_POINT_TITLE1,
                                                SELLER_TOUR_ROUTE_COLLECTION_POINT_DESCRIPTION1_IN_DB,
                                                1,
                                                1
                                                )
        createtour.click_element('Крестик в маршруте в создании тура продавца')
        page.wait_for_timeout(2000)
        # assertions.check_svg_near_text('Идентификатор отеля')
        # createtour.fill_element('HotelID в создании тура продавца', SELLER_TOUR_HOTELID)                                            #ТЕПЕРЬ ПРОЖИВАНИЕ
        # createtour.fill_element('Ссылка на HotelID в создании тура продавца', SELLER_TOUR_HOTELID_LINK)
        # createtour.click_element('Кнопка Сохранить в создании тура продавца')
        # page.wait_for_timeout(2000)
        # assertions.check_field_value_from_locator('HotelID в создании тура продавца', SELLER_TOUR_HOTELID)
        # page.wait_for_timeout(1000)
        # assertions.check_field_value_from_locator('Ссылка на HotelID в создании тура продавца', SELLER_TOUR_HOTELID_LINK)
        # assertions.check_create_tour_in_db_with_hotelid(db_connection, SELLER_TOUR_TITLE1, SELLER_TOUR_HOTELID, SELLER_TOUR_HOTELID_LINK)
        assertions.check_operator_tour_create_status_front( page, SELLER_TOUR_STATUS3_ALL_FILL)
        assertions.check_operator_tour_param_button_on_review_active()
        createtour.click_element('Кнопка на проверку в создании туру')
        createtour.click_element('Кнопка Проживания не будет в создании тура')
        createtour.click_element('Кнопка подтвердить модерацию в создании тура')
        page.wait_for_timeout(5000) 
        assertions.check_operator_tour_create_status_front( page, SELLER_TOUR_STATUS4_ON_CHECK)
        assertions.check_create_tour_all_with_general_fields_disable(SELLER_TOUR_CLASS_DISABLE)
        assertions.check_tour_status_in_db(db_connection, SELLER_TOUR_TITLE1, 2)
        assertions.check_request_statuses(intercept_requests)
        createtour.delete_tour_in_db(db_connection, db_connection_dev_logs, SELLER_TOUR_TITLE1)


    @allure.title('Проверка, что нельзя отправить тур на модерацию без обязательных данных из параметров тура')
    def test_seller_create_tour20 (self, db_connection, page: Page, photo_paths, db_connection_dev_logs):
        createtour = SellerCreateUpdateTourWaypoints(page)
        assertions = AssertionsTourWaypoints(page)
        createtour.delete_tour_in_db(db_connection, db_connection_dev_logs, SELLER_TOUR_TITLE1)
        createtour.seller_goto_create_tour_old(page, SELLER_LOGIN4_TOURS, SELLER_PASSWORD1)
        createtour.fill_all_tour_without_route(page, photo_paths, SELLER_TOUR_TITLE1,
                                                                        True,
                                                                        SELLER_TOUR_DESCRIPTION1,
                                                                        SELLER_TOUR_INPRICE1,
                                                                        SELLER_TOUR_NOT_IN_INPRICE1
                                                                        )
        assertions.check_operator_tour_param_button_on_review_inactive()
        page.wait_for_timeout(5000)
        createtour.check_absence_button_on_check(page)
        createtour.seller_waypoints_fill_collection_point(page, photo_paths, SELLER_TOUR_ROUTE_COLLECTION_POINT_ADDRESS1,
                                                                SELLER_TOUR_ROUTE_COLLECTION_POINT_TIME1,
                                                                SELLER_TOUR_ROUTE_COLLECTION_POINT_TITLE1,
                                                                SELLER_TOUR_ROUTE_COLLECTION_POINT_DESCRIPTION1
                                                                  )
        assertions.check_operator_tour_param_button_on_review_active()
        createtour.check_presence_button_on_check(page)
        createtour.fill_element('Что не входит в стоимость в создании тура продавца', '')
        assertions.check_operator_tour_param_button_on_review_active()
        createtour.check_presence_button_on_check(page)
        createtour.click_element('Кому подойдет1 в создании тура продавца')
        assertions.check_operator_tour_param_button_on_review_active()
        createtour.check_presence_button_on_check(page)
        # createtour.fill_element('HotelID в создании тура продавца', '')
        # createtour.fill_element('Ссылка на HotelID в создании тура продавца', '')
        assertions.check_operator_tour_param_button_on_review_active()
        createtour.check_presence_button_on_check(page)
        createtour.fill_element('Название тура в параметрах тура', '')
        assertions.check_operator_tour_param_button_on_review_inactive()
        createtour.fill_element('Название тура в параметрах тура', SELLER_TOUR_TITLE1)
        createtour.click_element('Только предварительное бронирование тогл в параметрах тура')
        assertions.check_operator_tour_param_button_on_review_active()
        createtour.check_presence_button_on_check(page)
        createtour.click_element('1й жанр в параметрах тура')
        assertions.check_operator_tour_param_button_on_review_inactive()
        createtour.check_absence_button_on_check(page)
        createtour.click_element('1й жанр в параметрах тура')
        createtour.fill_element('Описание в создании тура продавца', '')
        assertions.check_operator_tour_param_button_on_review_inactive()
        createtour.check_absence_button_on_check(page)
        createtour.fill_element('Описание в создании тура продавца', SELLER_TOUR_DESCRIPTION1)
        createtour.fill_element('Что входит в стоимость в создании тура продавца', '')
        assertions.check_operator_tour_param_button_on_review_inactive()
        createtour.check_absence_button_on_check(page)
        createtour.fill_element('Что входит в стоимость в создании тура продавца',  SELLER_TOUR_INPRICE1)
        createtour.click_element('Кнопка удалить для Фото5 в создании тура продавца')
        createtour.click_element('Кнопка подтверждающая удаления фото в создании тура продавца')
        page.wait_for_timeout(1000) 
        assertions.check_operator_tour_param_button_on_review_inactive()
        createtour.check_absence_button_on_check(page) 
        createtour.click_element('Назад в создании тура')
        createtour.delete_tour_in_db(db_connection, db_connection_dev_logs, SELLER_TOUR_TITLE1)
        createtour.click_element('кнопка Создать в списке туров')
        createtour.fill_all_tour_without_route_class_transport(page, photo_paths, SELLER_TOUR_TITLE1,
                                                                        True,
                                                                        SELLER_TOUR_DESCRIPTION1,
                                                                        SELLER_TOUR_INPRICE1,
                                                                        SELLER_TOUR_NOT_IN_INPRICE1
                                                                        )
        createtour.seller_waypoints_fill_collection_point(page, photo_paths, SELLER_TOUR_ROUTE_COLLECTION_POINT_ADDRESS1,
                                                                SELLER_TOUR_ROUTE_COLLECTION_POINT_TIME1,
                                                                SELLER_TOUR_ROUTE_COLLECTION_POINT_TITLE1,
                                                                SELLER_TOUR_ROUTE_COLLECTION_POINT_DESCRIPTION1
                                                                  )
        createtour.click_element('На своей машине в параметрах тура')
        assertions.check_operator_tour_param_button_on_review_inactive()
        createtour.check_absence_button_on_check(page)
        page.wait_for_timeout(2000) 
        createtour.click_element('Назад в создании тура')
        createtour.delete_tour_in_db(db_connection, db_connection_dev_logs, SELLER_TOUR_TITLE1)
        createtour.click_element('кнопка Создать в списке туров')
        createtour.fill_all_tour_without_route_class_transport(page, photo_paths, SELLER_TOUR_TITLE1,
                                                                        True,
                                                                        SELLER_TOUR_DESCRIPTION1,
                                                                        SELLER_TOUR_INPRICE1,
                                                                        SELLER_TOUR_NOT_IN_INPRICE1
                                                                        )
        createtour.seller_waypoints_fill_collection_point(page, photo_paths, SELLER_TOUR_ROUTE_COLLECTION_POINT_ADDRESS1,
                                                                SELLER_TOUR_ROUTE_COLLECTION_POINT_TIME1,
                                                                SELLER_TOUR_ROUTE_COLLECTION_POINT_TITLE1,
                                                                SELLER_TOUR_ROUTE_COLLECTION_POINT_DESCRIPTION1
                                                                  )
        createtour.click_element('1й класс в параметрах тура')
        assertions.check_operator_tour_param_button_on_review_inactive()
        createtour.check_absence_button_on_check(page)
        createtour.click_element('На своей машине в параметрах тура')
        assertions.check_operator_tour_param_button_on_review_active()
        createtour.check_presence_button_on_check(page)
        createtour.delete_tour_in_db(db_connection, db_connection_dev_logs, SELLER_TOUR_TITLE1)

        