
from Constants.const_general import URL
import json
#URL
BASKET_PAGE_URL = f'{URL}basket'
YOUR_PAYMENT_URL = 'https://sandbox.ypmn.ru/pay/v2/'
#Пустая корзина
CLIENT_BASKET_EMPTY_H1_VALUE = 'Моя корзина'
CLIENT_BASKET_EMPTY_H2_VALUE = 'Здесь пока пусто'
CLIENT_BASKET_EMPTY_DESCRIPTION_VALUE = 'Совсем скоро здесь может быть ваше идеальное автопутешествие!'
#Данные путешественника
C_CLIENT_BASKET_LASTNAME = 'Тимошин'
C_CLIENT_BASKET_NAME = 'Никита'
C_CLIENT_BASKET_PATRONYMIC = 'Олегович'
C_CLIENT_BASKET_PHONE = '79999999999'
C_CLIENT_BASKET_EMAIL = 'nikitatimoshinpost1@yahoo.com'
C_CLIENT_BASKET_EMAIL2 = 'nikitatimoshinpost@gmail.com'
C_CLIENT_BASKET_EMAIL3 = 'nikitatimoshinpost@gmail.com12345'
C_CLIENT_BASKET_EMAIL4 = 'nikitatimoshinpost'
C_CLIENT_BASKET_DATE_BORN = '27.03.1995'
#Данные путешественника ошибки
C_CLIENT_BASKET_LASTNAME_ERROR = 'Поле Фамилия обязательно'
C_CLIENT_BASKET_NAME_ERROR = 'Поле Имя обязательно'
C_CLIENT_BASKET_EMAIL_ERROR = 'Поле Email обязательно'
C_CLIENT_BASKET_EMAIL_ERROR2 = 'Введите корректный email'
C_CLIENT_BASKET_DATE_BORN_ERROR = 'Поле Дата рождения обязательно'
#Промокоды
C_CLIENT_BASKET_PROMOCODE_NON_EXISTENT = 'ghfdfhj'
C_CLIENT_BASKET_PROMOCODE1 = 'автотест1'
C_CLIENT_BASKET_PROMOCODE2 = 'автотест2'
C_CLIENT_BASKET_PROMOCODE3 = 'автотест3'
C_CLIENT_BASKET_PROMOCODE4 = 'автотест4'
C_CLIENT_BASKET_PROMOCODE5 = 'автотест5'
C_CLIENT_BASKET_PROMOCODE6 = 'автотест6'
C_CLIENT_BASKET_PROMOCODE7 = 'автотест7'
#Ошибки
C_CLIENT_BASKET_ERROR1 = 'Заполните данные основного участника'
C_CLIENT_BASKET_ERROR2 = 'Не хватает мест на выбранную дату в туре'
C_CLIENT_BASKET_ERROR3 = 'не найден промокод'
C_CLIENT_BASKET_ERROR4 = 'Промокод неактивен'
C_CLIENT_BASKET_ERROR5 = 'Срок действия промокода закончился'
C_CLIENT_BASKET_ERROR6 = 'к-во использований промокода закончилось'
C_CLIENT_BASKET_ERROR7 = 'Такое значение поля email уже существует.'
C_CLIENT_BASKET_ERROR8 = 'Некорректные данные пользователя'
C_CLIENT_BASKET_ERROR9 = 'Заполните данные покупателя'
# Твои платежи
C_CLIENT_BASKET_PAYMENT_CARD = '4652035440667037'
C_CLIENT_BASKET_PAYMENT_CODE = '971'
C_CLIENT_BASKET_PAYMENT_NAME = 'Timoshin Nikita'
C_CLIENT_BASKET_PAYMENT_SUMMA1 = '3,774.00 RUB'
C_CLIENT_BASKET_PAYMENT_SUMMA2 = '12,000.00 RUB'
C_CLIENT_BASKET_PAYMENT_SUMMA3 = '3,824.00 RUB'
C_CLIENT_BASKET_PAYMENT_SUMMA4 = '12,050.00 RUB'
C_CLIENT_BASKET_PAYMENT_SUMMA5 = '3,509.82 RUB'
C_CLIENT_BASKET_PAYMENT_SUMMA6 = '3,674.00 RUB'
C_CLIENT_BASKET_PAYMENT_SUMMA7 = '3,774.00 RUB'
C_CLIENT_BASKET_PAYMENT_SUMMA8 = '3,556.32 RUB'
C_CLIENT_BASKET_PAYMENT_SUMMA9 = '3,724.00 RUB'
C_CLIENT_BASKET_PAYMENT_SUMMA10 = '1,350.00 RUB'
C_CLIENT_BASKET_PAYMENT_SUMMA11 = '11,160.00 RUB'
C_CLIENT_BASKET_PAYMENT_SUMMA12 = '11,900.00 RUB'
C_CLIENT_BASKET_PAYMENT_SUMMA13 = '62,000.00 RUB'
C_CLIENT_BASKET_PAYMENT_SUMMA14 = '11,206.50 RUB'
C_CLIENT_BASKET_PAYMENT_SUMMA15 = '11,950.00 RUB'
C_CLIENT_BASKET_PAYMENT_SUMMA16 = '1,950.00 RUB'
C_CLIENT_BASKET2_PAYMENT_SUMMA1 = '4,820.00 RUB'
C_CLIENT_BASKET3_INSURANCE_PAYMENT_SUMMA1 = '3,690.00 RUB'
C_CLIENT_BASKET3_INSURANCE_PAYMENT_SUMMA2 = '4,110.00 RUB'
C_CLIENT_BASKET3_INSURANCE_PAYMENT_SUMMA3 = '32,580.00 RUB'
C_CLIENT_BASKET3_INSURANCE_PAYMENT_SUMMA4 = '33,000.00 RUB'
C_CLIENT_BASKET3_INSURANCE_PAYMENT_SUMMA5 = '4,614.00 RUB'
C_CLIENT_BASKET3_INSURANCE_PAYMENT_SUMMA6 = '5,076.00 RUB'
C_CLIENT_BASKET3_INSURANCE_PAYMENT_SUMMA7 = '45,483.00 RUB'
C_CLIENT_BASKET3_INSURANCE_PAYMENT_SUMMA8 = '46,050.00 RUB'
C_CLIENT_BASKET3_INSURANCE_PAYMENT_SUMMA9 = '2,436.00 RUB'
C_CLIENT_BASKET2_PAYMENT_SUMMA1 = '8,374.00 RUB'
#Страница успешной оплаты
C_CLIENT_SUCCESSUFUL_PAYMENT_TITLE = 'Заказ успешно оформлен'
C_CLIENT_SUCCESSUFUL_PAYMENT_DESCRIPTION = 'Платеж обрабатывается, но вы уже можете отслеживать свой заказ в разделе «Мои туры». При успешной оплате, мы отправим код в смс и на ваш email. По прибытии на точку сбора, сообщите код организатору.'
C_CLIENT_SUCCESSUFUL_PAYMENT_BUTTON = ' Перейти в Мои автотуры'
#Общее для всех заказов и подзаказов
C_CLIENT_BASKET_TOUR1_ORDER_STATUS1_DB1 = 1 
C_CLIENT_BASKET_TOUR1_ORDER_STATUS2_DB1 = 2
C_CLIENT_BASKET_TOUR1_SUBORDER_STATUS1_DB1 = 1
C_CLIENT_BASKET_TOUR1_SUBORDER_STATUS2_DB1 = 2
C_CLIENT_BASKET_TOUR1_SUBORDER_TYPE_DB1 = 'buy'
C_CLIENT_BASKET_TOUR1_SUBORDER_TYPE_DB2 = 'booking'
C_CLIENT_BASKET_TOUR1_SUBORDER_COMMISSION_DB1 = 12
C_CLIENT_BASKET_TOUR2_SUBORDER_COMMISSION_DB1 = 15

# ПЕРВЫЙ ТУР
CLIENT_BASKET_TOUR1_BUY_ID = 1601
CLIENT_BASKET_TOUR1_BUY_A = f'{URL}tour/avtotest-tur-ne-nuzno-trogat-1601-0913'
CLIENT_BASKET_TOUR1_TITLE = 'Автотест Тур, не нужно трогать'
C_CLIENT_BASKET_TOUR1_FORMAT = 'Кастомный тур'
C_CLIENT_BASKET_TOUR1_CLASS = 'Комфорт'

#Первый кейс для тура1 - Персональный
CLIENT_BASKET_TOUR1_DATE_START1 = '1 март, 2028 10:00 - '
CLIENT_BASKET_TOUR1_DATE_END1 = '3 март, 2028 '
C_CLIENT_BASKET_TOUR1_PRICE1 = '3774 ₽'
C_CLIENT_BASKET_TOUR1_OPTIONS1 = '0 ₽'
C_CLIENT_BASKET_TOUR1_ALL_PRICE1 = '3774 ₽'
#Первый кейс для тура1 в БД
#Заказ1
C_CLIENT_BASKET_TOUR1_ORDER_USERID_DB = 5010
C_CLIENT_BASKET_TOUR1_ORDER_SUMMA_DB1 = 3774.00
#Заказ1 - #Подзаказ1
C_CLIENT_BASKET_TOUR1_SUBORDER_RACEID_DB1 = 4284
C_CLIENT_BASKET_TOUR1_SUBORDER_SUMMA_DB1 = 3774.00
C_CLIENT_BASKET_TOUR1_SUBORDER_TOURS_SUMMA_DB1 = 3774.00
C_CLIENT_BASKET_TOUR1_SUBORDER_TOURS_DISCOUNT_DB1 = 0.00
C_CLIENT_BASKET_TOUR1_SUBORDER_OPTIONS_SUMMA_DB1 = 0.00
C_CLIENT_BASKET_TOUR1_SUBORDER_TIME_DB1 = '10:00'
C_CLIENT_BASKET_TOUR1_SUBORDER_PARTICIPANTS_DB1 = json.loads('''[{"price_id":457,"amount":1},{"price_id":458,"amount":2},{"price_id":459,"amount":3},{"price_id":460,"amount":4},{"price_id":461,"amount":5}]''')
C_CLIENT_BASKET_TOUR1_SUBORDER_NUMBER_TRAVELERS_DB1 = 0
#Общие цены
C_CLIENT_BASKET_TOURS1 = '3774 ₽'
C_CLIENT_BASKET_OPTIONS1 = '0 ₽'
C_CLIENT_BASKET_NUMBER_TRAVELERS1 = '15'
C_CLIENT_BASKET_ALL_PRICE1 = '3774 ₽'

#Второй кейс для тура1 - Групповой
CLIENT_BASKET_TOUR1_DATE_START2 = '2 март, 2028 10:00 - '
CLIENT_BASKET_TOUR1_DATE_END2 = '4 март, 2028 '
C_CLIENT_BASKET_TOUR1_PRICE2 = '12000 ₽'
C_CLIENT_BASKET_TOUR1_OPTIONS2 = '0 ₽'
C_CLIENT_BASKET_TOUR1_ALL_PRICE2 = '12000 ₽'
#Второй кейс для тура1 в БД
#Заказ2
C_CLIENT_BASKET_TOUR1_ORDER_SUMMA_DB2 = 12000.00
C_CLIENT_BASKET_TOUR1_SUBORDER_NUMBER_TRAVELERS_DB2 = 3
#Заказ2 -#Подзаказ1
C_CLIENT_BASKET_TOUR1_SUBORDER_TOURID_DB2 = 1601
C_CLIENT_BASKET_TOUR1_SUBORDER_RACEID_DB2 = 4318
C_CLIENT_BASKET_TOUR1_SUBORDER_SUMMA_DB2 = 12000.00
C_CLIENT_BASKET_TOUR1_SUBORDER_TOURS_SUMMA_DB2 = 12000.00
C_CLIENT_BASKET_TOUR1_SUBORDER_TOURS_DISCOUNT_DB2 = 0.00
C_CLIENT_BASKET_TOUR1_SUBORDER_OPTIONS_SUMMA_DB2 = 0.00
#Общие цены
C_CLIENT_BASKET_TOURS2 = '12000 ₽'
C_CLIENT_BASKET_OPTIONS2 = '0 ₽'
C_CLIENT_BASKET_NUMBER_TRAVELERS2 = '3'
C_CLIENT_BASKET_ALL_PRICE2 = '12000 ₽'

#Третий кейс для тура1 - Персональный с опциями
C_CLIENT_BASKET_TOUR1_OPTIONS3 = '50 ₽'
C_CLIENT_BASKET_TOUR1_ALL_PRICE3 = '3824 ₽'
#Общие цены
C_CLIENT_BASKET_OPTIONS3 = '50 ₽'
C_CLIENT_BASKET_ALL_PRICE3 = '3824 ₽'
#Третий кейс для тура1 в БД
C_CLIENT_BASKET_TOUR1_ORDER_SUMMA_DB3 = 3824.00
#Заказ3 - #Подзаказ1
C_CLIENT_BASKET_TOUR1_SUBORDER_TOURS_SUMMA_DB3 = 3824.00
C_CLIENT_BASKET_TOUR1_SUBORDER_SUMMA_DB3 = 3824.00
C_CLIENT_BASKET_TOUR1_SUBORDER_OPTIONS_SUMMA_DB3 = 50.00

#Четвертый кейс для тура1 - Персональный с опциями
C_CLIENT_BASKET_TOUR1_OPTIONS4 = '50 ₽'
C_CLIENT_BASKET_TOUR1_ALL_PRICE4 = '12050 ₽'
#Общие цены
C_CLIENT_BASKET_OPTIONS4 = '50 ₽'
C_CLIENT_BASKET_ALL_PRICE4 = '12050 ₽'
#Четвертый кейс для тура1 в БД
C_CLIENT_BASKET_TOUR1_ORDER_SUMMA_DB4 = 12050.00
#Заказ4 - #Подзаказ1
C_CLIENT_BASKET_TOUR1_SUBORDER_TOURS_SUMMA_DB4 = 12050.00
C_CLIENT_BASKET_TOUR1_SUBORDER_SUMMA_DB4 = 12050.00
C_CLIENT_BASKET_TOUR1_SUBORDER_OPTIONS_SUMMA_DB4 = 50.00

#Пятый кейс для тура1 - Покупка персонального тура c промокодом1
#Общие цены
C_CLIENT_BASKET_ALL_PRICE_BEFORE_DISCOUNT5 = '3774 ₽'
C_CLIENT_BASKET_ALL_PRICE_AFTER_DISCOUNT5 = '3509.82 ₽'
#Пятый кейс для тура1 в БД
C_CLIENT_BASKET_TOUR1_ORDER_SUMMA_DB5 = 3509.82
C_CLIENT_BASKET_TOUR1_ORDER_PROCODEID_DB5 =1247
#Заказ4 - #Подзаказ1
C_CLIENT_BASKET_TOUR1_SUBORDER_TOURS_SUMMA_DB5 = 3509.82
C_CLIENT_BASKET_TOUR1_SUBORDER_SUMMA_DB5 = 3509.82
C_CLIENT_BASKET_TOUR1_SUBORDER_TOURS_DISCOUNT_DB5 = 264.18

#Шестой кейс для тура1 - Покупка персонального тура c промокодом2
#Общие цены
C_CLIENT_BASKET_ALL_PRICE_BEFORE_DISCOUNT6 = '3774 ₽'
C_CLIENT_BASKET_ALL_PRICE_AFTER_DISCOUNT6 = '3674.00 ₽'
#Шестой кейс для тура1 в БД
C_CLIENT_BASKET_TOUR1_ORDER_SUMMA_DB6 = 3674.00
C_CLIENT_BASKET_TOUR1_ORDER_PROCODEID_DB6 =1248
#Заказ4 - #Подзаказ1
C_CLIENT_BASKET_TOUR1_SUBORDER_TOURS_SUMMA_DB6 = 3674.00
C_CLIENT_BASKET_TOUR1_SUBORDER_SUMMA_DB6 = 3674.00
C_CLIENT_BASKET_TOUR1_SUBORDER_TOURS_DISCOUNT_DB6 = 100.00

#Седьмой кейс для тура1 - Покупка персонального тура c сменой количества уч.
#Цены в туре
C_CLIENT_BASKET_TOUR1_PRICE7 = '2220 ₽'
C_CLIENT_BASKET_TOUR1_ALL_PRICE7 = '2220 ₽'
#Общие цены
C_CLIENT_BASKET_NUMBER_TRAVELERS7 = '10'
C_CLIENT_BASKET_TOURS7 = '2220 ₽'
C_CLIENT_BASKET_ALL_PRICE7 = '2220 ₽'

#Восьмой кейс для тура1 - Покупка персонального тура с опциями c с промокодом1
#Цены в туре
C_CLIENT_BASKET_TOUR1_ALL_PRICE8 = '3824 ₽'
#Общие цены
C_CLIENT_BASKET_ALL_PRICE_BEFORE_DISCOUNT8 = '3824 ₽'
C_CLIENT_BASKET_ALL_PRICE_AFTER_DISCOUNT8 = '3556.32 ₽'
#Восьмой кейс для тура1 в БД
C_CLIENT_BASKET_TOUR1_ORDER_SUMMA_DB8 = 3556.32
#Заказ4 - #Подзаказ1
C_CLIENT_BASKET_TOUR1_SUBORDER_TOURS_SUMMA_DB8 = 3556.32
C_CLIENT_BASKET_TOUR1_SUBORDER_SUMMA_DB8 = 3556.32
C_CLIENT_BASKET_TOUR1_SUBORDER_TOURS_DISCOUNT_DB8 = 267.68      

#Девятый кейс для тура1 - Покупка персонального тура с опциями c с промокодом2
#Общие цены
C_CLIENT_BASKET_ALL_PRICE_BEFORE_DISCOUNT9 = '3824 ₽'
C_CLIENT_BASKET_ALL_PRICE_AFTER_DISCOUNT9 = '3724.00 ₽'
#Девятый кейс для тура1 в БД
C_CLIENT_BASKET_TOUR1_ORDER_SUMMA_DB9 = 3724.00
#Заказ4 - #Подзаказ1
C_CLIENT_BASKET_TOUR1_SUBORDER_TOURS_SUMMA_DB9 = 3724.00
C_CLIENT_BASKET_TOUR1_SUBORDER_SUMMA_DB9 = 3724.00
C_CLIENT_BASKET_TOUR1_SUBORDER_TOURS_DISCOUNT_DB9 = 100.00  

#Десятый кейс для тура1 - Покупка персонального тура с комментарием
C_CLIENT_BASKET_COMMENT = '''Тут комментарий к заказу.
Пожалуйста прочтите!'''

#Одинадцатый кейс для тура1 - Покупка группового тура с промокодом1
#Общие цены
C_CLIENT_BASKET_ALL_PRICE_BEFORE_DISCOUNT11 = '12000 ₽'
C_CLIENT_BASKET_ALL_PRICE_AFTER_DISCOUNT11 = '11160.00 ₽'
#Одинадцатый кейс для тура1 в БД
C_CLIENT_BASKET_TOUR1_ORDER_SUMMA_DB11 = 11160.0
C_CLIENT_BASKET_TOUR1_ORDER_PROCODEID_DB11 =1247
#Заказ4 - #Подзаказ1
C_CLIENT_BASKET_TOUR1_SUBORDER_TOURS_SUMMA_DB11 = 11160.00
C_CLIENT_BASKET_TOUR1_SUBORDER_SUMMA_DB11 = 11160.00
C_CLIENT_BASKET_TOUR1_SUBORDER_TOURS_DISCOUNT_DB11 = 840.00

#Двенадцатый кейс для тура1 - Покупка группового тура с промокодом2
#Общие цены
C_CLIENT_BASKET_ALL_PRICE_BEFORE_DISCOUNT12 = '12000 ₽'
C_CLIENT_BASKET_ALL_PRICE_AFTER_DISCOUNT12 = '11900.00 ₽'
#Двенадцатый кейс для тура1 в БД
C_CLIENT_BASKET_TOUR1_ORDER_SUMMA_DB12 = 11900.00
#Заказ4 - #Подзаказ1
C_CLIENT_BASKET_TOUR1_SUBORDER_TOURS_SUMMA_DB12 = 11900.00
C_CLIENT_BASKET_TOUR1_SUBORDER_SUMMA_DB12 = 11900.00
C_CLIENT_BASKET_TOUR1_SUBORDER_TOURS_DISCOUNT_DB12 = 100.00 

#Тринадцатый кейс для тура1 - Покупка группового c изменением количества уч.
C_CLIENT_BASKET_TOUR1_PRICE13 = '62000 ₽'
C_CLIENT_BASKET_TOUR1_ALL_PRICE13 = '62000 ₽'
#Общие цены
C_CLIENT_BASKET_NUMBER_TRAVELERS13 = '13'
C_CLIENT_BASKET_TOURS13 = '62000 ₽'
C_CLIENT_BASKET_ALL_PRICE13 = '62000 ₽'
C_CLIENT_BASKET_TOUR1_ORDER_SUMMA_DB13 = 62000.00
C_CLIENT_BASKET_TOUR1_SUBORDER_NUMBER_TRAVELERS_DB13 = 13
#Заказ4 - #Подзаказ1
C_CLIENT_BASKET_TOUR1_SUBORDER_TOURS_SUMMA_DB13 = 62000.00
C_CLIENT_BASKET_TOUR1_SUBORDER_SUMMA_DB13 = 62000.00

#Четырнадцатый кейс для тура1 - Покупка группового тура с опциями с промокодом1
#Цены в туре
C_CLIENT_BASKET_TOUR1_ALL_PRICE14 = '12050 ₽'
#Общие цены
C_CLIENT_BASKET_ALL_PRICE_BEFORE_DISCOUNT14 = '12050 ₽'
C_CLIENT_BASKET_ALL_PRICE_AFTER_DISCOUNT14 = '11206.50 ₽'
#Четырнадцатый кейс для тура1 в БД
C_CLIENT_BASKET_TOUR1_ORDER_SUMMA_DB14 = 11206.50
#Заказ4 - #Подзаказ1
C_CLIENT_BASKET_TOUR1_SUBORDER_TOURS_SUMMA_DB14 = 11206.50
C_CLIENT_BASKET_TOUR1_SUBORDER_SUMMA_DB14 = 11206.50
C_CLIENT_BASKET_TOUR1_SUBORDER_TOURS_DISCOUNT_DB14 = 843.50  

#Пятнадцатый кейс для тура1 - Покупка группового тура с опциями с промокодом2
#Общие цены
C_CLIENT_BASKET_ALL_PRICE_BEFORE_DISCOUNT15 = '12050 ₽'
C_CLIENT_BASKET_ALL_PRICE_AFTER_DISCOUNT15 = '11950.00 ₽'
#Пятнадцатый кейс для тура1 в БД
C_CLIENT_BASKET_TOUR1_ORDER_SUMMA_DB15 = 11950.00
#Заказ4 - #Подзаказ1
C_CLIENT_BASKET_TOUR1_SUBORDER_TOURS_SUMMA_DB15 = 11950.00
C_CLIENT_BASKET_TOUR1_SUBORDER_SUMMA_DB15 = 11950.00
C_CLIENT_BASKET_TOUR1_SUBORDER_TOURS_DISCOUNT_DB15 = 100.00  

#Шестнадцатый кейс для тура1 - Покупка группового тура с комментарием
C_CLIENT_BASKET_COMMENT2 = '''Сюрприз-путешествие на годовщину родителей (55 лет вместе). Просьба сохранять конфиденциальность при коммуникации. Особые пожелания: романтический ужин на берегу моря, фотосессия на закате, букет из 55 роз в номере, организовать поздравление от детей по видеосвязи во время ужина. Родители не знают о поездке - все детали согласовывать только со мной.'''

#Двадцать третий кейс для тура1 - Покупка персонального тура с выбором времени в карточке тура
CLIENT_BASKET_TOUR1_DATE_START23 = '4 март, 2028 14:14 - '
CLIENT_BASKET_TOUR1_DATE_END23 = '6 март, 2028 '
#Двадцать третий для тура1 в БД
#Заказ1 - #Подзаказ1
C_CLIENT_BASKET_TOUR1_SUBORDER_RACEID_DB23 = 5055
C_CLIENT_BASKET_TOUR1_SUBORDER_TIME_DB23 = '14:14'
C_CLIENT_BASKET_TOUR1_SUBORDER_PARTICIPANTS_DB23 = json.loads('''[{"price_id":2183,"amount":1},{"price_id":2184,"amount":2},{"price_id":2185,"amount":3},{"price_id":2186,"amount":4},{"price_id":2187,"amount":5}]''')

#Двадцать четвертый кейс для тура1 - Покупка группового тура с выбором времени в карточке тура и без сверхлимита
CLIENT_BASKET_TOUR1_DATE_START24 = '5 март, 2028 14:14 - '
CLIENT_BASKET_TOUR1_DATE_END24 = '7 март, 2028 '
#Двадцать четвертый для тура1 в БД
#Заказ1 - #Подзаказ1
C_CLIENT_BASKET_TOUR1_SUBORDER_RACEID_DB24 = 5054
C_CLIENT_BASKET_TOUR1_SUBORDER_TIME_DB24 = '14:14'


#ВТОРОЙ ТУР (Для составного заказа)
CLIENT_BASKET_TOUR2_BUY_ID = 2660
CLIENT_BASKET_TOUR2_BUY_A = f'{URL}tour/avtotest-tur-vtoroi-ne-nuzno-trogat-2660-1491'
CLIENT_BASKET_TOUR2_TITLE = 'Автотест Тур Второй, не нужно трогать'
C_CLIENT_BASKET_TOUR2_FORMAT = 'Автопутешествие'


#Первый кейс для тура1 + тур2 - Покупка персонального тура c опциями+ бронирование с опциями группового
CLIENT_BASKET_TOUR2_DATE_START1 = '3 февр, 2028 11:11 - '
CLIENT_BASKET_TOUR2_DATE_END1 = '5 февр, 2028 '
C_CLIENT_BASKET_TOUR2_PRICE1 = '4500 ₽'
C_CLIENT_BASKET_TOUR2_OPTIONS1 = '50 ₽'
C_CLIENT_BASKET_TOUR2_ALL_PRICE1 = '4550 ₽'
C_CLIENT_BASKET_TOUR2_ALL_PRICE2 = '3300 ₽'
#Заказ1
C_CLIENT_BASKET_TOUR2_ORDER_USERID_DB1 = 5010
C_CLIENT_BASKET_TOUR2_ORDER_SUMMA_DB1 = 8374.00
#Заказ1 -#Подзаказ1
    #Уже есть у первого тура
#Заказ1 -#Подзаказ2
C_CLIENT_BASKET_TOUR2_SUBORDER_TOURID_DB1 = 2660
C_CLIENT_BASKET_TOUR2_SUBORDER_RACEID_DB1 = 3723
C_CLIENT_BASKET_TOUR2_SUBORDER_SUMMA_DB1 = 4550.00
C_CLIENT_BASKET_TOUR2_SUBORDER_TOURS_SUMMA_DB1 = 4550.00
C_CLIENT_BASKET_TOUR2_SUBORDER_TOURS_DISCOUNT_DB1 = 0.00
C_CLIENT_BASKET_TOUR2_SUBORDER_OPTIONS_SUMMA_DB1 = 50.00
#Общие цены
C_CLIENT_BASKET2_TOURS1 = '8274 ₽'
C_CLIENT_BASKET2_OPTIONS1 = '100 ₽'
C_CLIENT_BASKET2_NUMBER_TRAVELERS1 = '20'
C_CLIENT_BASKET2__ALL_PRICE1 = '8374 ₽'


#АЛЬФА-СТРАХОВАНИЕ
#Сет страхуемых1
C_CLIENT_BASKET_INSURANCE_LASTNAME1 = 'Первов'
C_CLIENT_BASKET_INSURANCE_NAME1 = 'Перв'
C_CLIENT_BASKET_INSURANCE_PATRONYMIC1 = 'Первовович'
C_CLIENT_BASKET_INSURANCE_BIRTH1 = '01.03.1995'

C_CLIENT_BASKET_INSURANCE_LASTNAME2 = 'Второв'
C_CLIENT_BASKET_INSURANCE_NAME2 = 'Втор'
C_CLIENT_BASKET_INSURANCE_PATRONYMIC2 = 'Вторович'
C_CLIENT_BASKET_INSURANCE_BIRTH2 = '02.03.2024'

C_CLIENT_BASKET_INSURANCE_LASTNAME3 = 'Третьев'
C_CLIENT_BASKET_INSURANCE_NAME3 = 'Трет'
C_CLIENT_BASKET_INSURANCE_PATRONYMIC3 = 'Третович'
C_CLIENT_BASKET_INSURANCE_BIRTH3 = '03.03.1953'

C_CLIENT_BASKET_INSURANCE_LASTNAME4 = 'Четверов'
C_CLIENT_BASKET_INSURANCE_NAME4 = 'Четр'
C_CLIENT_BASKET_INSURANCE_PATRONYMIC4 = 'Четрович'
C_CLIENT_BASKET_INSURANCE_BIRTH4 = '04.03.1947'

C_CLIENT_BASKET_INSURANCE_LASTNAME5 = 'Пятов'
C_CLIENT_BASKET_INSURANCE_NAME5 = 'Пят'
C_CLIENT_BASKET_INSURANCE_PATRONYMIC5 = 'Пятович'
C_CLIENT_BASKET_INSURANCE_BIRTH5 = '05.03.1944'

C_CLIENT_BASKET_INSURANCE_LASTNAME6 = 'Шестов'
C_CLIENT_BASKET_INSURANCE_NAME6 = 'Шест'
C_CLIENT_BASKET_INSURANCE_PATRONYMIC6 = 'Шестович'
C_CLIENT_BASKET_INSURANCE_BIRTH6 = '02.03.2018' 

#Корзина со страховкой кейс1 - Разные значения. Тип страховки 1. Персональный.
C_CLIENT_BASKET_INSURANCE_DATES1 = '1 мар. 2028 – 3 мар. 2028'
#Тур
C_CLIENT_BASKET_INSURANCE_TOUR1_PRICE1 = '1110 ₽'
C_CLIENT_BASKET_INSURANCE_TOUR1_ALL_PRICE1 = '1110 ₽'
#Заказ1
C_CLIENT_BASKET_INSURANCE_TOUR1_ORDER_SUMMA_DB1 = 3690.00
#Заказ1 - #Подзаказ1
C_CLIENT_BASKET_INSURANCE_TOUR1_SUBORDER_SUMMA_DB1 = 1110.00
C_CLIENT_BASKET_INSURANCE_TOUR1_SUBORDER_TOURS_SUMMA_DB1 = 1110.00
C_CLIENT_BASKET_INSURANCE_TOUR1_SUBORDER_PARTICIPANTS_DB1 = json.loads('''[{"price_id":457,"amount":1},{"price_id":458,"amount":1},{"price_id":459,"amount":1},{"price_id":460,"amount":2},{"price_id":461,"amount":1}]''')
#Общие цены
C_CLIENT_BASKET_INSURANCE_NUMBER_TRAVELERS1 = '6'
C_CLIENT_BASKET_INSURANCE_TOURS_PRICE1 = '1110 ₽'
C_CLIENT_BASKET_INSURANCE_PRICE1 = '0 ₽'
C_CLIENT_BASKET_INSURANCE_PRICE1_2 = '2580 ₽'
C_CLIENT_BASKET_INSURANCE_ALL_PRICE1 = '1110 ₽'
C_CLIENT_BASKET_INSURANCE_ALL_PRICE1_2 = '3690 ₽'

#Корзина со страховкой кейс2 - Разные значения. Тип страховки 2. Персональный.
#Заказ1
C_CLIENT_BASKET_INSURANCE_TOUR1_ORDER_SUMMA_DB2 = 4110.00
#Общие цены
C_CLIENT_BASKET_INSURANCE_PRICE2 = '3000 ₽'
C_CLIENT_BASKET_INSURANCE_ALL_PRICE2 = '4110 ₽'

#Корзина со страховкой кейс3 - Разные значения. Тип страховки 1. Групповой.
C_CLIENT_BASKET_INSURANCE_DATES3 = '2 мар. 2028 – 4 мар. 2028'   
#Тур
C_CLIENT_BASKET_INSURANCE_TOUR1_PRICE3 = '30000 ₽'
C_CLIENT_BASKET_INSURANCE_TOUR1_ALL_PRICE3 = '30000 ₽'
#Заказ1
C_CLIENT_BASKET_INSURANCE_TOUR1_ORDER_SUMMA_DB3 = 32580.00
#Заказ1 - #Подзаказ1
C_CLIENT_BASKET_INSURANCE_TOUR1_SUBORDER_SUMMA_DB3 = 30000.00
C_CLIENT_BASKET_INSURANCE_TOUR1_SUBORDER_TOURS_SUMMA_DB3 = 30000.00
C_CLIENT_BASKET__INSURANCE_TOUR1_SUBORDER_NUMBER_TRAVELERS_DB3 = 6 
C_CLIENT_BASKET_INSURANCE_TOURS_PRICE3 = '30000 ₽'
C_CLIENT_BASKET_INSURANCE_PRICE3 = '2580 ₽'
C_CLIENT_BASKET_INSURANCE_ALL_PRICE3_1 = '30000 ₽'
C_CLIENT_BASKET_INSURANCE_ALL_PRICE3_2 = '32580 ₽'
C_CLIENT_BASKET_TOUR1_SUBORDER_PARTICIPANTS_DB3 = []
C_CLIENT_BASKET_TOUR1_SUBORDER_NUMBER_TRAVELERS_DB3 = 6

#Корзина со страховкой кейс4 - Разные значения. Тип страховки 2. Групповой.
#Заказ1
C_CLIENT_BASKET_INSURANCE_TOUR1_ORDER_SUMMA_DB4 = 33000.00
#Общие цены
C_CLIENT_BASKET_INSURANCE_PRICE4 = '3000 ₽'
C_CLIENT_BASKET_INSURANCE_ALL_PRICE4 = '33000 ₽'

#Сет страхуемых2 - Граничные значения
C_CLIENT_BASKET_INSURANCE_BORDER_DATES1 = '1 мар. 2026 – 3 мар. 2026'
C_CLIENT_BASKET_INSURANCE_BORDER_LASTNAME1 = 'Первовг'
C_CLIENT_BASKET_INSURANCE_BORDER_NAME1 = 'Первг'
C_CLIENT_BASKET_INSURANCE_BORDER_PATRONYMIC1 = 'Первововичг'
C_CLIENT_BASKET_INSURANCE_BORDER_BIRTH1 = '12.02.2026' #Будущие нельзя вставить даты рождения, пока наиболее близкое к 0 лет

C_CLIENT_BASKET_INSURANCE_BORDER_LASTNAME2 = 'Второвг'
C_CLIENT_BASKET_INSURANCE_BORDER_NAME2 = 'Вторг'
C_CLIENT_BASKET_INSURANCE_BORDER_PATRONYMIC2 = 'Второвичг'
C_CLIENT_BASKET_INSURANCE_BORDER_BIRTH2 = '02.03.2020'

C_CLIENT_BASKET_INSURANCE_BORDER_LASTNAME3 = 'Третьевг'
C_CLIENT_BASKET_INSURANCE_BORDER_NAME3 = 'Третг'
C_CLIENT_BASKET_INSURANCE_BORDER_PATRONYMIC3 = 'Третовичг'
C_CLIENT_BASKET_INSURANCE_BORDER_BIRTH3 = '01.03.2020'

C_CLIENT_BASKET_INSURANCE_BORDER_LASTNAME4 = 'Четверовг'
C_CLIENT_BASKET_INSURANCE_BORDER_NAME4 = 'Четрг'
C_CLIENT_BASKET_INSURANCE_BORDER_PATRONYMIC4 = 'Четровичг'
C_CLIENT_BASKET_INSURANCE_BORDER_BIRTH4 = '02.03.1958'

C_CLIENT_BASKET_INSURANCE_BORDER_LASTNAME5 = 'Пятовг'
C_CLIENT_BASKET_INSURANCE_BORDER_NAME5 = 'Пятг'
C_CLIENT_BASKET_INSURANCE_BORDER_PATRONYMIC5 = 'Пятовичг'
C_CLIENT_BASKET_INSURANCE_BORDER_BIRTH5 = '01.03.1958'

C_CLIENT_BASKET_INSURANCE_BORDER_LASTNAME6 = 'Шестовг'
C_CLIENT_BASKET_INSURANCE_BORDER_NAME6 = 'Шестг'
C_CLIENT_BASKET_INSURANCE_BORDER_PATRONYMIC6 = 'Шестовичг'
C_CLIENT_BASKET_INSURANCE_BORDER_BIRTH6 = '02.03.1953' 

C_CLIENT_BASKET_INSURANCE_BORDER_LASTNAME7 = 'Седьмовг'
C_CLIENT_BASKET_INSURANCE_BORDER_NAME7 = 'Седьмг'
C_CLIENT_BASKET_INSURANCE_BORDER_PATRONYMIC7 = 'Седьмовичг'
C_CLIENT_BASKET_INSURANCE_BORDER_BIRTH7 = '01.03.1953' 

C_CLIENT_BASKET_INSURANCE_BORDER_LASTNAME8 = 'Восьмовг'
C_CLIENT_BASKET_INSURANCE_BORDER_NAME8 = 'Восмг'
C_CLIENT_BASKET_INSURANCE_BORDER_PATRONYMIC8 = 'Восьмовичг'
C_CLIENT_BASKET_INSURANCE_BORDER_BIRTH8 = '02.03.1948' 

C_CLIENT_BASKET_INSURANCE_BORDER_LASTNAME9 = 'Девятовг'
C_CLIENT_BASKET_INSURANCE_BORDER_NAME9 = 'Девятг'
C_CLIENT_BASKET_INSURANCE_BORDER_PATRONYMIC9 = 'Девятовичг'
C_CLIENT_BASKET_INSURANCE_BORDER_BIRTH9 = '01.03.1948' 

#Корзина со страховкой кейс5 - Граничные значения. Тип страховки 1. Персональный.
#Тур
C_CLIENT_BASKET_INSURANCE_TOUR1_PRICE5 = '1776 ₽'
C_CLIENT_BASKET_INSURANCE_TOUR1_ALL_PRICE5 = '1776 ₽'
#Заказ1
C_CLIENT_BASKET_INSURANCE_TOUR1_ORDER_SUMMA_DB5 = 4614.00
#Заказ1 - #Подзаказ1
C_CLIENT_BASKET_INSURANCE_TOUR1_SUBORDER_SUMMA_DB5 = 1776.00
C_CLIENT_BASKET_INSURANCE_TOUR1_SUBORDER_TOURS_SUMMA_DB5 = 1776.00
C_CLIENT_BASKET_INSURANCE_TOUR1_SUBORDER_PARTICIPANTS_DB5 = json.loads('''[{"price_id":457,"amount":2},{"price_id":458,"amount":2},{"price_id":459,"amount":2},{"price_id":460,"amount":2},{"price_id":461,"amount":1}]''')
#Общие цены
C_CLIENT_BASKET_INSURANCE_NUMBER_TRAVELERS5 = '9'
C_CLIENT_BASKET_INSURANCE_TOURS_PRICE5 = '1776 ₽'
C_CLIENT_BASKET_INSURANCE_PRICE5 = '2838 ₽'
C_CLIENT_BASKET_INSURANCE_ALL_PRICE5 = '1776 ₽'
C_CLIENT_BASKET_INSURANCE_ALL_PRICE5_2 = '4614 ₽'

#Корзина со страховкой кейс6 - Граничные значения. Тип страховки 2. Персональный.
#Заказ1
C_CLIENT_BASKET_INSURANCE_TOUR1_ORDER_SUMMA_DB6 = 5076.00
#Общие цены
C_CLIENT_BASKET_INSURANCE_PRICE6 = '3300 ₽'
C_CLIENT_BASKET_INSURANCE_ALL_PRICE6 = '5076 ₽'

#Корзина со страховкой кейс7 - Граничные значения. Тип страховки 1. Групповой.
#Тур
C_CLIENT_BASKET_INSURANCE_TOUR1_PRICE7 = '42000 ₽'
C_CLIENT_BASKET_INSURANCE_TOUR1_ALL_PRICE7 = '42000 ₽'
# #Заказ1
C_CLIENT_BASKET_INSURANCE_TOUR1_ORDER_SUMMA_DB7 = 45483.00
# #Заказ1 - #Подзаказ1
C_CLIENT_BASKET_INSURANCE_TOUR1_SUBORDER_SUMMA_DB7 = 42000.00
C_CLIENT_BASKET_INSURANCE_TOUR1_SUBORDER_TOURS_SUMMA_DB7 = 42000.00
C_CLIENT_BASKET_TOUR1_SUBORDER_NUMBER_TRAVELERS_DB7 = 9
#Общие цены
C_CLIENT_BASKET_INSURANCE_NUMBER_TRAVELERS7 = '9'
C_CLIENT_BASKET_INSURANCE_TOURS_PRICE7 = '42000 ₽'
C_CLIENT_BASKET_INSURANCE_PRICE7 = '3483 ₽'
C_CLIENT_BASKET_INSURANCE_ALL_PRICE7 = '42000 ₽'
C_CLIENT_BASKET_INSURANCE_ALL_PRICE7_2 = '45483 ₽'

#Корзина со страховкой кейс8 - Граничные значения. Тип страховки 2. Групповой.
#Заказ1
C_CLIENT_BASKET_INSURANCE_TOUR1_ORDER_SUMMA_DB8 = 46050.00
#Общие цены
C_CLIENT_BASKET_INSURANCE_PRICE8 = '4050 ₽'
C_CLIENT_BASKET_INSURANCE_ALL_PRICE8 = '46050 ₽'

#Корзина со страховкой кейс9 - Проверка, что промокод не действует на страховку и меньше страхуемых. Разные значения. Тип страховки 1. Персональный.
#Заказ1
C_CLIENT_BASKET_INSURANCE_TOUR1_ORDER_SUMMA_DB9 = 2436.00
#Заказ1 - #Подзаказ1
C_CLIENT_BASKET_INSURANCE_TOUR1_SUBORDER_SUMMA_DB9 = 888.00
C_CLIENT_BASKET_INSURANCE_TOUR1_SUBORDER_TOURS_SUMMA_DB9 = 888.00
C_CLIENT_BASKET_INSURANCE_TOUR1_SUBORDER_TOURS_DISCOUNT_DB9 = 222.00  
#Общие цены
C_CLIENT_BASKET_INSURANCE_PRICE9 = '1548 ₽'
C_CLIENT_BASKET_INSURANCE_ALL_PRICE9_1_BEFORE = '1110 ₽'
C_CLIENT_BASKET_INSURANCE_ALL_PRICE9_1_AFTER = '888.00 ₽'
C_CLIENT_BASKET_INSURANCE_ALL_PRICE9_2_BEFORE = '2658 ₽'
C_CLIENT_BASKET_INSURANCE_ALL_PRICE9_2_AFTER = '2436.00 ₽'